### ISSUE TITLE
Failed to load https://updates.jenkins.io/download/plugins/

### ISSUE THREAD

**Issue by midosh** [jenkins-infra/helpdesk#4369] opened 2024-10-28 15:13 UTC
### Service(s)

plugins.jenkins.io

### Summary

Caused: java.io.IOException: Failed to load https://updates.jenkins.io/download/plugins/ionicons-api/74.v93d5eb_813d5f/ionicons-api.hpi to /var/jenkins_home/plugins/ionicons-api.jpi.tmp
        at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1334)
Caused: java.io.IOException: Failed to download from https://updates.jenkins.io/download/plugins/ionicons-api/74.v93d5eb_813d5f/ionicons-api.hpi (redirected to: https://2.mirrors.in.sahilister.net/jenkins/plugins/ionicons-api/74.v93d5eb_813d5f/ionicons-api.hpi)

**Comment by MarkEWaite** [comment] 2024-10-28 15:28
I'm unable to duplicate the issue from my computer.  The mirror provides the plugin file as expected.  Are you still seeing the issue?  If you are, then you'll probably need to check the network where your Jenkins controller is running.  If it is blocked from accessing the mirror, you'll need to request that it be unblocked.

If other mirrors are available to you, you can download interactively from one of them through the '?mirrorlist' page like:

https://updates.jenkins.io/latest/ionicons-api.hpi?mirrorlist

**Comment by dduportal** [comment] 2024-10-28 15:53
Hi @midosh , I can't reproduce either.It looks like your network does not allow to reach the download mirror at https://2.mirrors.in.sahilister.net/jenkins/.

Could you post a screenshot of the web page https://get.jenkins.io/plugins/ionicons-api/74.v93d5eb_813d5f/ionicons-api.hpi?mirrorlist so we can evaluate the mirror redirection system?

Also, what is the result of the following command in the network where your Jenkins controller:

```shell
curl --verbose --location https://2.mirrors.in.sahilister.net/jenkins/plugins/ionicons-api/74.v93d5eb_813d5f/ionicons-api.hpi
```

?

**Comment by MarkEWaite** [comment] 2024-10-28 21:59
> I have deployed Jenkins on a Kubernetes cluster using the `jenkins/jenkins:2.462.3-lts-jdk17` image.

The image that you pasted seems to hint that your Kubernetes cluster is unable to access either the IPv4 address or the IPv6 address of that update server.  You'll need to check with the administrators of the cluster to understand why it can't access those addresses.

**Comment by dduportal** [comment] 2024-10-29 10:18
Thanks folks. I confirm: the error is not on the Jenkins infrastructure:

- We cannot reproduce
- No one else raised the same problem
- The provided screenshot demonstrates that there is an issue in your infrastructure @midosh which prevents requests to go from your Jenkins pod to the https://2.mirrors.in.sahilister.net/jenkins/ mirror.

**Comment by dduportal** [comment] 2024-10-29 10:20
@midosh the Jenkins infra team provides an API, updated once a day at https://reports.jenkins.io/infrastructure/v2/index.json which lists the IPv4 and IPv6 of each mirror to help automating network egress rules for end users. That might help.

However I realize the the sahilister mirror listed in the API is the old one which redirects to a new set of IPs. We are working on fixing this before closing the issue.

**Comment by dduportal** [comment] 2024-10-29 10:28
- Fixed the (private internal documentation to use the new sahilister DNS as mirror name) https://github.com/jenkins-infra/runbooks/commit/6889e3c4b8c01fcc0d9e46d1ad669f761df47eb6 
- Which automatically fixed the automated report generation: https://reports.jenkins.io/infrastructure/v2/index.json

**Comment by dduportal** [comment] 2024-10-29 10:28
@midosh I'm closing this issue as there no more actionables for the Jenkins infra team.

**Closed by dduportal** 2024-10-29 10:28 UTC
Labels: plugins.jenkins.io
