### ISSUE TITLE
Suspend Confluence Publisher plugin due to closed source dependency

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#3856] opened 2023-12-10 18:53 UTC
### Service(s)

Update center

### Summary

The [Confluence Publisher plugin](https://plugins.jenkins.io/confluence-publisher/) is using dependencies that are closed source and are not licensed with an OSI-approved open source license. The Jenkins [project governance document](https://www.jenkins.io/project/governance/#license) and the [hosting page](https://www.jenkins.io/doc/developer/publishing/preparation/#license) state that we deliver plugins with open source licenses.

We should suspend distribution of the Confluence Publisher plugin.

The specific license of concern is:

* [Atlassian Customer Agreement](https://www.atlassian.com/legal/customer-agreement)

From the `/plugin/confluence-publisher/wrapper/thirdPartyLicenses` page of a Jenkins installation that includes the Confluence Publisher plugin:

Using the [Atlassian Customer Agreement](https://www.atlassian.com/legal/customer-agreement):

* `com.atlassian.confluence:confluence-java-api:7.14.0`
* `com.atlassian.confluence:confluence-rest-client:7.14.0`
* `com.atlassian.confluence:confluence-rest-serialization:7.14.0`
* `com.atlassian.confluence:confluence-rest-api:7.14.0`

### Reproduction steps

1. Install Jenkins 2.426.1 (or any other recent Jenkins version).
2. Install the Confluence Publisher plugin.
3. Open the `/plugin/confluence-publisher/wrapper/thirdPartyLicenses` URL and confirm the abovementioned license is visible.

**Comment by MarkEWaite** [comment] 2023-12-11 01:34
I've sent an email message to the maintainers of the plugin with a copy to the Jenkins board.  The maintainers are:

* @jetersen
* @jhansche

**Comment by NotMyFault** [comment] 2023-12-11 07:23
Approved.

**Comment by basil** [comment] 2023-12-11 21:17
I've submitted a documentation pull request to the Confluence Publisher plugin repository explaining why it will be suspended:

- https://github.com/jenkinsci/confluence-publisher-plugin/pull/160

**Comment by MarkEWaite** [comment] 2023-12-12 16:19
Closing as complete because the pull requests have been merged:

* https://github.com/jenkins-infra/update-center2/pull/756
* https://github.com/jenkinsci/confluence-publisher-plugin/pull/160

Confirmed that the [updates.jenkins.io/latest](https://updates.jenkins.io/latest/) is no longer listing confluence-publisher as a distributed plugin.  Confirmed with my local Jenkins controller that confluence-publisher was listed in the update center from 18 hours ago and is no longer listed in the current update center.

Plugins site is not yet updated to show that the plugin is no longer distributed.  I assume we'll need several more hours before it is visible there.

* https://plugins.jenkins.io/confluence-publisher/

**Closed by MarkEWaite** 2023-12-12 16:19 UTC
Labels: triage, updateCenter

**Comment by amarjit25** [comment] 2024-05-06 13:27
what is the alternate of confluence publisher plugin to push the jenkins build information to Confluence

**Comment by MarkEWaite** [comment] 2024-05-06 13:38
> what is the alternate of confluence publisher plugin to push the jenkins build information to Confluence

I think that you could contact Atlassian for their recommendations. try the [Atlassian command line interface](https://marketplace.atlassian.com/apps/10886/atlassian-command-line-interface-cli), or try the [Confluence command line interface](https://marketplace.atlassian.com/apps/284/confluence-command-line-interface-cli).
