### ISSUE TITLE
All highmem jobs are stuck in queue

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#2971] opened 2022-06-02 22:33 UTC
### Service(s)

ci.jenkins.io

### Summary

Currently, several ATH jobs are building on several highmem nodes which appear all to be stuck. There's no new high memory node coming online either, causing new ATH jobs to be stuck in the build queue while existing ones are stalled.

There's one high memory node in the "launching" phase, but I can't see that there's any progress.

**Comment by MarkEWaite** [comment] 2022-06-03 01:45
Also shown by the [check agent availability job](https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/check-agent-availability) job on ci.jenkins.io

**Comment by dduportal** [comment] 2022-06-03 05:43
- Set Jenkins in "safe mode" (builds are queued but not executed
- Had to stop manually all the running builds: they all were stuck trying to contact their executors. It's weird because I expect timeout to kick: smells liek a bug :(
- For each stopped build, triggered a build (that was queued)
- Restarting Jenkins

**Comment by dduportal** [comment] 2022-06-03 05:45
Another weird thing: the EC2 higmem agents are not started by the scheduler. Trying to spawn a few manually.

**Comment by dduportal** [comment] 2022-06-03 05:50
- Ref. https://github.com/jenkinsci/acceptance-test-harness/pull/780#issuecomment-1143581911 2 days ago.
- It sounds like that the Azure VM High mem are always the ones stuck

**Comment by dduportal** [comment] 2022-06-03 05:58
Side note: there has been issues with repo.jenkins-ci.org during the past 9 hours:

<img width="1777" alt="Capture d’écran 2022-06-03 à 07 57 49" src="https://user-images.githubusercontent.com/1522731/171795602-2c200585-3787-4d99-a9d4-c8b547c2cdb9.png">

**Comment by dduportal** [comment] 2022-06-03 06:53
OH: I missed the new features of the azure-vm-agents plugin about VM retention (the "Idle retention" was the only one available last time I checked) and the ability to limit amount of VMs per kind of template 

<img width="1331" alt="Capture d’écran 2022-06-03 à 08 49 36" src="https://user-images.githubusercontent.com/1522731/171802557-479cc504-49e0-46d3-8822-b41ef6df7ece.png">


- We should switch to the "one shot" retention strategy on all our controllers
- That explains the "suspended" state
- We might want to update the azure vm config to only have one azure cloud (requires puppet template overhaul) so only one GC

**Comment by timja** [comment] 2022-06-03 07:46
Those features have been there forever, although need to check I didn't break the once one by reconnecting

**Comment by dduportal** [comment] 2022-06-03 07:49
> 

I wonder if Olivier and I missed it because of the UI last year then, but I'm 101% sure we did not find it. not sure that it would fix the root issue there but would help.

**Comment by dduportal** [comment] 2022-06-03 07:51
@timja Weird: there are a lot of azure agents on ci.j, but on Azure portal I don't see them.
Logs are telling "reconnect", which feels weird, as if the azure VM GC was not picking it up.
I've tried the "save cloud config on UI" but did not change, so I'm going to:
- stop the puppet agent
- apply the "once retention strategy" manually

**Comment by timja** [comment] 2022-06-03 07:52
I'm wondering if this had some unintended consequences:
https://github.com/jenkinsci/azure-vm-agents-plugin/pull/359

**Comment by timja** [comment] 2022-06-03 07:52
Can revert if needed

**Comment by dduportal** [comment] 2022-06-03 07:54
> Can revert if needed

I would revert the plugin on ci.jenkins.io instead.

Would you need any logs or debug info to help tracking the plugin behavior?

**Comment by timja** [comment] 2022-06-03 07:57
> I would revert the plugin on ci.jenkins.io instead.

I can reproduce an issue with one shot strategy anyway, I don't have time to fix properly currently so going to revert for now

**Comment by dduportal** [comment] 2022-06-03 17:24
First step on the "retention" cleanup to "once applied in https://github.com/jenkins-infra/jenkins-infra/pull/2200

**Comment by dduportal** [comment] 2022-06-03 19:00
Closing as the queue has been cleaned up and agents are now in better shape.

**Closed by dduportal** 2022-06-03 19:00 UTC
Labels: ci.jenkins.io
