### ISSUE TITLE
unexpected content in https://get.jenkins.io/plugins/

### ISSUE THREAD

**Issue by jtnord** [jenkins-infra/helpdesk#4013] opened 2024-03-26 10:10 UTC
### Service(s)

get.jenkins.io

### Summary

https://get.jenkins.io/plugins/ contains a directory for published jenkins plugins.

however there are a few entries created yesterday for specific plugins in the root (not a directory for the plugin and then versions for the plugins).

<img width="557" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/494726/c44ae47c-31f4-43a5-9faa-7a2ea8d0f902">

### Reproduction steps

1. open https://get.jenkins.io/plugins/
2. look for non directory entries (expect none), notice there are a few from today and yesterday.   

Looks like something unexpected is going on

**Comment by lemeurherve** [comment] 2024-03-26 10:31
This is related to https://github.com/jenkins-infra/helpdesk/issues/3414#issuecomment-2019574326

On-going status (not reflecting everything): https://status.jenkins.io/issues/2024-03-25-update-center-maintenance/

**Comment by dduportal** [comment] 2024-03-26 11:08
Proceeding to remove the files from the shared storage (will report here)

**Comment by dduportal** [comment] 2024-03-26 11:19
- Files removed (using Azure Storage explorer)
- Disabled update-center2 to avoid files being recreated
- This unexpected behavior is most probably due to https://github.com/jenkins-infra/mirror-scripts/commit/1d61ac01ecda18a06404d6833e499f74eadf8fc7#diff-47359663b8a943374726a5b9a5e030386eaa2fb3968196651d896a78571459d3R55 and would also explain why update-center2 keeps re-delivering the same plugins since yesterday: they are not copied on the proper location

**Comment by dduportal** [comment] 2024-03-26 16:35
As per https://github.com/jenkins-infra/helpdesk/issues/3414#issuecomment-2020935685, this issue is now fixed.

Many thanks @jtnord for reporting! It helped us a lot!

**Closed by dduportal** 2024-03-26 16:35 UTC
Labels: updateCenter, get.jenkins.io
