### ISSUE TITLE
Cannot apt upgrade Jenkins from 2.348 using pkg.jenkins-ci.org

### ISSUE THREAD

**Issue by Mavelous** [jenkins-infra/helpdesk#3020] opened 2022-06-24 16:37 UTC
### Service(s)

Other

### Summary

```
$ cat /etc/apt/sources.list.d/jenkins.list 
deb http://pkg.jenkins-ci.org/debian binary/

$ apt update
Hit:1 http://mirrors.linode.com/debian buster InRelease
Hit:2 http://mirrors.linode.com/debian-security buster/updates InRelease
Hit:3 http://mirrors.linode.com/debian buster-updates InRelease
Ign:4 http://pkg.jenkins-ci.org/debian binary/ InRelease
Hit:5 http://pkg.jenkins-ci.org/debian binary/ Release
Reading package lists... Done
Building dependency tree       
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
$ apt list --upgradable
Listing... Done
jenkins/binary 2.356 all [upgradable from: 2.348]
N: There are 281 additional versions. Please use the '-a' switch to see them.
$ apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  jenkins
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 87.2 MB of archives.
After this operation, 142 kB disk space will be freed.
Do you want to continue? [Y/n] 
Err:1 http://pkg.jenkins-ci.org/debian binary/ jenkins 2.356
  404  Not Found [IP: 52.202.51.185 80]
E: Failed to fetch http://pkg.jenkins-ci.org/debian/binary/jenkins_2.356_all.deb  404  Not Found [IP: 52.202.51.185 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

### Reproduction steps

1. apt update
2. apt upgrade
3. Receive error message:
```Err:1 http://pkg.jenkins-ci.org/debian binary/ jenkins 2.356
  404  Not Found [IP: 52.202.51.185 80]
E: Failed to fetch http://pkg.jenkins-ci.org/debian/binary/jenkins_2.356_all.deb  404  Not Found [IP: 52.202.51.185 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?```

**Comment by Mavelous** [comment] 2022-06-24 16:38
This was fixed by changing my `/etc/apt/sources.list.d/jenkins.list` file to:

`deb http://pkg.jenkins.io/debian binary/`

The issue is only with `pkg.jenkins-ci.org`

**Comment by dduportal** [comment] 2022-06-24 16:57
Hi @Mavelous, the current instructions to install the Jenkins stable version are mentioning both using `HTTPS` for the scheme + using the domain jenkins.io: https://pkg.jenkins.io/debian-stable/ for LTS and https://pkg.jenkins.io/debian/ for weekly.

=> you would benefit to use the jenkins.io domain, as it's cached by Fastly.

I assume that this "change" in behavior was caused by https://www.jenkins.io/blog/2022/05/13/mirrors/ indirectly.

However we're going to check if cannot add an HTTP redirection from `pkg.jenkins-ci.org` to `pkg.jenkins.io` so that old URL won't be broken anymore.

Thanks for reporting!

**Comment by dduportal** [comment] 2022-06-28 15:46
Assigning to @smerle33 as discussed during the team meeting.

Goal: add the 2 redirections below in the Apache vhost configuration generated by the puppet profiles, only for pkg.origing.jenkins.io VM:
- http://pkg.jenkins-ci.org(.*) => http**S**://pkg.jenkins.io($1)
- http**S**://pkg.jenkins-ci.org(.*) => http**S**://pkg.jenkins.io($1)

**Comment by dduportal** [comment] 2022-07-04 08:05
Redirections are in place since 4 days: closing.

**Closed by dduportal** 2022-07-04 08:05 UTC
Labels: pkg.jenkins.io
