### ISSUE TITLE
Plugin “Monitoring” v1.92.0 not available via get.jenkins.io

### ISSUE THREAD

**Issue by marvinruder** [jenkins-infra/helpdesk#3413] opened 2023-02-27 08:51 UTC
### Service(s)

get.jenkins.io

### Summary

Plugin “Monitoring” v1.92.0 not available via get.jenkins.io although being released at [https://repo.jenkins-ci.org](https://repo.jenkins-ci.org/releases/org/jvnet/hudson/plugins/monitoring/1.92.0/monitoring-1.92.0.hpi)

Also discussed in https://issues.jenkins.io/browse/JENKINS-70688.

### Reproduction steps

1. Navigate to https://plugins.jenkins.io/monitoring/#releases
2. Click Installation options – Download – direct link
3. Observe that the direct link leads to https://get.jenkins.io/plugins/monitoring/1.92.0/monitoring.hpi, which answers with “Not Found”

Also:

1. On a Jenkins server with Monitoring 1.91.0 installed, navigate to `/manage/pluginManager/updates/`
2. Select plugin “Monitoring” and attempt to update it
3. Observe the following error message:

![](https://issues.jenkins.io/secure/attachment/60017/IMG_8845.jpeg)

**Comment by timja** [comment] 2023-02-27 08:54
Duplicate of https://github.com/jenkins-infra/helpdesk/issues/3411

(duplicate / root cause)

**Closed by timja** 2023-02-27 08:54 UTC
Labels: triage, get.jenkins.io

**Comment by smerle33** [comment] 2023-02-27 10:29
<img width="1588" alt="Capture d’écran 2023-02-27 à 11 28 19" src="https://user-images.githubusercontent.com/95630726/221539453-4b1720d2-9712-4507-81bf-21522ce6eb5a.png">
we applied a fix in #3411, the `monitoring` plugin is now visible in version v1.92.0
