### ISSUE TITLE
Find a way to monitor jobs done from private controllers

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#3592] opened 2023-05-24 12:00 UTC
There are some jobs we'd like to monitor like the Jenkins Core Docker image publication or Update Center jobs, but as they're done from private controllers like trusted.ci.jenkins.io where we can't install Datadog.
We have to figure out a way to publish these jobs results in a public/accessible place so we could analyse them without being connected to trusted.ci.jenkins.io

It could be the creation of logs/report files in a bucket for example.

**Comment by timja** [comment] 2023-05-24 12:52
Why can't datadog be installed?

**Comment by dduportal** [comment] 2023-05-24 13:37
It's about the "invasive" part, but more about the data transmitted.
The container logs are OK most of the time, but not the build logs / credentials for instance.

It's a way to limit the risks of "accidentally exporting" sensitive data

**Comment by timja** [comment] 2023-05-24 14:02
can't you turn that off in datadog config?

**Comment by dduportal** [comment] 2023-05-24 14:14
> can't you turn that off in datadog config?

probably, but it means it's opt-out: ok for ci.jenkins.io and infra.ci, but not ok for trusted.ci or release.ci for instance

**Comment by timja** [comment] 2023-05-24 14:59
This says it's off by default:
https://docs.datadoghq.com/integrations/jenkins/#datadog-agent-forwarding-using-environment-variables

**Comment by dduportal** [comment] 2023-05-24 15:03
> This says it's off by default: https://docs.datadoghq.com/integrations/jenkins/#datadog-agent-forwarding-using-environment-variables

Thats for using the "Jenkins datadog plugin" -> "datadog agent forward" but not really for the "don't send build log/data, only keep the build status".

**Comment by lemeurherve** [comment] 2023-06-27 13:48
Related to / duplicate of https://github.com/jenkins-infra/helpdesk/issues/2488

**Comment by dduportal** [comment] 2024-12-03 14:33
Duplicate of #2843

**Closed by dduportal** 2024-12-03 14:33 UTC
Labels: datadog, trusted.ci.jenkins.io
