### ISSUE TITLE
Cant install or update plugins because updates.jenkins.io redirects to mirror.yandex.ru

### ISSUE THREAD

**Issue by anonimus-asuseeepc** [jenkins-infra/helpdesk#4160] opened 2024-07-01 08:53 UTC
### Describe your use-case which is not covered by existing documentation.

Could not find appropriate category for this, but during plugin intallation or update getting this:
`java.net.SocketTimeoutException: Connect timed out
Caused: java.io.IOException: Failed to load https://updates.jenkins.io/download/plugins/veracode-scan/24.2.23.0/veracode-scan.hpi to /opt/jenkins/home/plugins/veracode-scan.jpi.tmp
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1334)
Caused: java.io.IOException: Failed to download from https://updates.jenkins.io/download/plugins/veracode-scan/24.2.23.0/veracode-scan.hpi (redirected to: https://mirror.yandex.ru/mirrors/jenkins/plugins/veracode-scan/24.2.23.0/veracode-scan.hpi)
`
RU sites are blocked by organization or ISP, not everything, but why jenkins cant use alternate mirrors? Are there any other mirrors?
Is this even normal that such redirect happens?

**Comment by dduportal** [comment] 2024-07-01 10:17
Hi @anonimus-asuseeepc , thanks for raising this issue.

We've migrated the issue to the jenkins-infra/helpdesk project which is the scope of the public Jenkins infrastructure (jenkins-infra/jenkins.io where you opened the issue initially is only for the website www.jenkins.io).

The problem you have has been already mentioned by other users in https://github.com/jenkins-infra/helpdesk/issues/4147#issuecomment-2196502394.

Let's continue the follow up in https://github.com/jenkins-infra/helpdesk/issues/4147: closing here as duplicate so it is easier to track.

**Closed by dduportal** 2024-07-01 10:17 UTC
Labels: mirrors.jenkins.io

**Comment by dduportal** [comment] 2024-07-01 11:14
As per https://github.com/jenkins-infra/helpdesk/issues/4147#issuecomment-2199767311, can you confirm the problem is fixed for you now?
