### ISSUE TITLE
Prevent creation of new issues in the WEBSITE project on Jira

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3268] opened 2022-11-29 16:31 UTC
### Service(s)

Jira

### Summary

The website components use GitHub issues as tracker, as integrated on jenkins.io footers, e.g., yet people raise new Jira issues sporadically.

I'd recommend we do the same we did to the HOSTING project, remove the WEBSITE project from the issue creation dropdown form.
That will leave all issues as-is, but prevent the creation of new issues on Jira.

**Comment by lemeurherve** [comment] 2022-12-06 13:15
@jenkins-infra/jira-admins WDYT about this proposition?

**Comment by timja** [comment] 2022-12-06 13:41
definitely block issues, that tracker hasn't been used in ages.

**Comment by daniel-beck** [comment] 2022-12-06 13:42
Sure, if nobody looks at Jira anymore, then we should stop accepting new issues.

Has anyone reviewed the old WEBSITE issues whether they should be migrated? INFRA was migrated with references to new issues, HOSTING had no open issues.

**Comment by daniel-beck** [comment] 2022-12-06 13:51
> I'm not sure if there is any value in that

I would not just throw them in the trash, never to be seen again. We don't need to automatically migrate everything, like was done for INFRA also for closed issues, but issues that have merit should not be lost just because we decided on a new issue tracker without a plan to deal with old issues.

**Comment by lemeurherve** [comment] 2022-12-06 13:53
I didn't imply to delete them from Jira, just wondering about migrating (copying) them over jenkins.io repo issues 🙂

**Comment by daniel-beck** [comment] 2022-12-06 13:56
Right, but if we now take this action to definitely abandon the old WEBSITE issue tracker, with nobody looking at it again, we should take this opportunity to review open issues and determine which are worthwhile.

"The trash" here does not necessarily mean deletion, having an issue tracker that's basically invisible is not much better.

**Comment by MarkEWaite** [comment] 2022-12-06 15:10
I think that @kmartens27 and I can review the open issues in the WEBSITE project and close them or recreate them on the www.jenkins.io GitHub repository.

**Comment by kmartens27** [comment] 2022-12-08 22:22
I have started reviewing the issues that @MarkEWaite was referring to, and will be discussing with him further for what should be transferred.

**Comment by lemeurherve** [comment] 2023-01-09 10:56
> Query that I'm using to process the queue is [issues.jenkins.io/issues/?jql=project%20%3D%20%22Jenkins%20Website%22%20and%20status%20not%20in%20(done)](https://issues.jenkins.io/issues/?jql=project%20%3D%20%22Jenkins%20Website%22%20and%20status%20not%20in%20(done))

@MarkEWaite @kmartens27 I see this list is now empty 🎉 

Is there anything remaining to do related to this issue or could it be closed as completed?

**Comment by kmartens27** [comment] 2023-01-09 14:06
@lemeurherve I believe this can be closed as completed. The tickets that are still relevant have been migrated to GitHub issue tracking, and all the WEBSITE tickets have been closed.

**Comment by lemeurherve** [comment] 2023-01-09 14:55
Ping @jenkins-infra/jira-admins, in order to close this issue can one of you remove the WEBSITE entry in the issue creation please?

<img width="451" alt="image" src="https://user-images.githubusercontent.com/91831478/211337416-137eb082-ac9c-4076-b44c-09d7bd715cf5.png">

**Comment by daniel-beck** [comment] 2023-01-09 18:26
> remove the WEBSITE entry in the issue creation

Should be done, please confirm.

**Comment by lemeurherve** [comment] 2023-01-09 18:27
Confirmed, thanks!

**Closed by lemeurherve** 2023-01-09 18:27 UTC
Labels: jira
