### ISSUE TITLE
openshift-jenkins docker image build fails with error "Failed to download plugin:<plugin name>"

### ISSUE THREAD

**Issue by mjayksharma** [jenkins-infra/helpdesk#4019] opened 2024-03-28 13:58 UTC
### Service(s)

release.ci.jenkins.io, community.jenkins.io, Docker Hub, Helpdesk, jenkins.io, mirrors.jenkins.io, plugins.jenkins.io

### Summary

I have below lines in our Dockerfile to build jenkins docker image for OpenShift
```COPY plugins.txt /opt/openshift/base-plugins.txt
COPY plugins.txt /opt/openshift/bundle-plugins.txt

RUN /usr/local/bin/install-jenkins-core-plugins.sh /opt/openshift/bundle-plugins.txt
```
When running docker build, the build fails with below error (failing on a different plugin everytime)

``````Jenkins version: 2.414.3


Analyzing war: /usr/share/java/jenkins.war
Checking JENKINS_WAR=/usr/share/java/jenkins.war

Analyzing war ... done

Downloading plugins...
Downloading plugin: ace-editor from https://updates.jenkins.io/download/plugins/ace-editor/1.1/ace-editor.hpi
Downloading plugin: ant from https://updates.jenkins.io/download/plugins/ant/487.vd79d090d4ea_e/ant.hpi
Downloading plugin: apache-httpcomponents-client-4-api from https://updates.jenkins.io/download/plugins/apache-httpcomponents-client-4-api/4.5.14-150.v7a_b_9d17134a_5/apache-httpcomponents-client-4-api.hpi
Downloading plugin: authentication-tokens from https://updates.jenkins.io/download/plugins/authentication-tokens/1.53.v1c90fd9191a_b_/authentication-tokens.hpi
Downloading plugin: blueocean-autofavorite from https://updates.jenkins.io/download/plugins/blueocean-autofavorite/1.2.5/blueocean-autofavorite.hpi
Downloading plugin: blueocean-bitbucket-pipeline from https://updates.jenkins.io/download/plugins/blueocean-bitbucket-pipeline/1.27.4/blueocean-bitbucket-pipeline.hpi
Downloading plugin: blueocean-commons from https://updates.jenkins.io/download/plugins/blueocean-commons/1.27.4/blueocean-commons.hpi
Downloading plugin: blueocean-commons-plugin from https://updates.jenkins.io/download/plugins/blueocean-commons-plugin/1.27.4/blueocean-commons-plugin.hpi
Failed to download plugin: blueocean-commons or blueocean-commons-plugin

``````

### Reproduction steps

Docker file:
``````##############################################
# Stage 1 : Build go-init
##############################################
#FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.20-openshift-4.15 AS go-init-builder
FROM --platform=linux/amd64 registry.abc.com/builder:rhel-8-golang-1.20-openshift-4.15 AS go-init-builder
ARG jenkins_version=latest
WORKDIR  /go/src/github.com/openshift/jenkins
COPY . .
WORKDIR  /go/src/github.com/openshift/jenkins/go-init
RUN GO111MODULE=off go build . && cp go-init /usr/bin

##############################################
# Stage 2 : Build slave-base with go-init
##############################################
#FROM registry.ci.openshift.org/ocp/4.15:cli
FROM --platform=linux/amd64 registry.abc.com/origin-cli:4.14.0
ARG jenkins_version=latest
COPY --from=go-init-builder /usr/bin/go-init /usr/bin/go-init

ENV JENKINS_VERSION=2 \
    HOME=/var/lib/jenkins \
    JENKINS_HOME=/var/lib/jenkins \
    JENKINS_UC=https://updates.jenkins.io \
    OPENSHIFT_JENKINS_IMAGE_VERSION=4.14 \
    LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8 \
    INSTALL_JENKINS_VIA_RPMS=false
# openshift/ocp-build-data will change INSTALL_JENKINS_VIA_RPMS to true
# so that the osbs/brew builds will install via RPMs; when this runs
# in api.ci, it will employ the old centos style, download the plugins and
# redhat-stable core RPM for download

LABEL io.k8s.description="Jenkins is a continuous integration server" \
    io.k8s.display-name="Jenkins 2" \
    io.openshift.tags="jenkins,jenkins2,ci" \
    io.openshift.expose-services="8080:http" \
    io.jenkins.version="${jenkins_version}" \
    io.openshift.s2i.scripts-url=image:///usr/libexec/s2i

# Labels consumed by Red Hat build service
LABEL com.redhat.component="openshift-jenkins-2-container" \
    name="openshift4/jenkins-2-rhel8" \
    architecture="x86_64" \
    maintainer="openshift-dev-services+jenkins@redhat.com"

# 8080 for main web interface, 50000 for slave agents
EXPOSE 8080 50000

# for backward compatibility with pre-3.6 installs leveraging a PV, where rpm installs went to /usr/lib64/jenkins, we are
# establishing a symbolic link for that guy as well, so that existing plugins in JENKINS_HOME/plugins pointing to
# /usr/lib64/jenkins will subsequently get redirected to /usr/lib/jenkins; it is confirmed that the 3.7 jenkins RHEL images
# do *NOT* have a /usr/lib64/jenkins path

COPY ./install_public_certs.sh .
RUN chmod +x install_public_certs.sh
RUN ./install_public_certs.sh
RUN ln -s /usr/lib/jenkins /usr/lib64/jenkins
RUN yum install -y dejavu-sans-fonts wget rsync gettext git git-lfs tar  zip  unzip  openssl  bzip2  java-11-openjdk  java-11-openjdk-devel  java-1.8.0-openjdk  java-1.8.0-openjdk-devel  jq  glibc-locale-source  xmlstarlet  glibc-langpack-en net-tools iputils nc python3 python3-pip

RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
RUN dnf upgrade -y
RUN yum update -y
RUN pip3 install jinja2
RUN pip3 install yq

#RUN yum install -y $INSTALL_PKGS && \
RUN yum update -y && \
    yum clean all  && \
    localedef -f UTF-8 -i en_US en_US.UTF-8 && \
    alternatives --family java-11 --install /usr/bin/java java /usr/lib/jvm/java-11-openjdk/bin/java 1  && \
    alternatives --set java java-11 && \
    alternatives --family javac-11 --install /usr/bin/javac javac /usr/lib/jvm/java-11-openjdk/bin/javac 1  && \
    alternatives --set javac javac-11 && \
    alternatives --family jar-11 --install /usr/bin/jar jar /usr/lib/jvm/java-11-openjdk/bin/jar 1  && \
    alternatives --set jar jar-11

COPY ./contrib/openshift /opt/openshift
COPY ./contrib/jenkins /usr/local/bin
ADD ./contrib/s2i /usr/libexec/s2i
ADD release.version /tmp/release.version

RUN rm /opt/openshift/bundle-plugins.txt && \
    rm /opt/openshift/base-plugins.txt
    
COPY plugins.txt /opt/openshift/base-plugins.txt
COPY plugins.txt /opt/openshift/bundle-plugins.txt

RUN /usr/local/bin/install-jenkins-core-plugins.sh /opt/openshift/bundle-plugins.txt && \
    rmdir /var/log/jenkins && \
    chmod -R 775 /etc/alternatives && \
    chmod -R 775 /var/lib/alternatives && \
    chmod -R 775 /usr/lib/jvm && \
    chmod 775 /usr/bin && \
    chmod 775 /usr/share/man/man1 && \
    mkdir -p /var/lib/origin && \
    chmod 775 /var/lib/origin && \
    chown -R 1001:0 /opt/openshift && \
    /usr/local/bin/fix-permissions /opt/openshift && \
    /usr/local/bin/fix-permissions /opt/openshift/configuration/init.groovy.d && \
    /usr/local/bin/fix-permissions /var/lib/jenkins && \
    /usr/local/bin/fix-permissions /var/log

# Add the cron job
COPY sync_plugins.sh /usr/src/app/sync_plugins.sh
RUN chmod +x /usr/src/app/sync_plugins.sh
RUN /usr/src/app/sync_plugins.sh
CMD ["sh", "-c", "while true; do /usr/src/app/sync_plugins.sh; sleep 3600; done"]
``````

Run docker build -t jenkins-master .

**Comment by dduportal** [comment] 2024-03-28 14:15
Hi @mjayksharma , your issue is absolutely not related to the `*.jenkins.io` infrastructure or websites. As such, I'm gonna close this issue as "Not planned" because there is nothing (at first sight) wrong in the Jenkins infrastructure.

Of course if you can provide details showing that there is an issue with these websites then we'll gladly reopen the issue and work on it.


It looks like your issue is a misconfiguration: could you raise the issue on the [community forums](https://community.jenkins.io) where you'll get help from the whole community (and not only from the Jenkins infra team members)?

A few notes along the way to provide better informations on your forum post:

- The shell script you are using to get the Jenkins plugins looks really old and is not supported since at least one year. Please check https://github.com/jenkinsci/docker?tab=readme-ov-file#install-plugins to see what is the recommended way (using the Java CLI [plugin manager](https://github.com/jenkinsci/plugin-installation-manager-tool/))

- Your example is NOT reproducible so it does not help. Could you try to provide a **minimalistic** example using public images please (ideally https://hub.docker.com/r/jenkins/jenkins)?
  - `registry.abc.com` does not exist, so we cannot retrieve the base images
  - You do not provide any of the files copied in the image through the numerous `COPY` instructions

- What is the exact Jenkins version used?
- What is the exact list of plugins (and their version if pinned)?

As a side note: https://plugins.jenkins.io/blueocean-commons-plugin does NOT exists while https://plugins.jenkins.io/blueocean-commons does.

**Closed by dduportal** 2024-03-28 14:15 UTC
