### ISSUE TITLE
ci.jenkins.io RPU PR The JAVA_HOME environment variable is not defined correctly

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#2732] opened 2022-01-13 11:07 UTC
### Service

ci.jenkins.io

### Summary

https://github.com/jenkins-infra/repository-permissions-updater/pull/2315

https://ci.jenkins.io/blue/organizations/jenkins/Infra%2Frepository-permissions-updater/detail/PR-2315/2/pipeline
> [2022-01-13T11:06:13.149Z] The JAVA_HOME environment variable is not defined correctly,
> [2022-01-13T11:06:13.149Z] this environment variable is needed to run this program.

**Comment by dduportal** [comment] 2022-01-18 20:11
I wonder if https://github.com/jenkins-infra/repository-permissions-updater/blob/ce2742a57059e93b2bd62c03991b484f04729a4f/Jenkinsfile#L43 shouldn't be set to `env.JAVA_HOME = tool 'jdk11' = tools 'jdk11-linux-static'` (because https://github.com/jenkins-infra/jenkins-infra/blob/production/dist/profile/templates/buildmaster/casc/tools.yaml.erb#L22).

**Comment by tfennelly** [comment] 2022-01-19 11:20
@dduportal hey Damien ... is there anything we can do to help move this along so we can get unblocked ?

**Comment by dduportal** [comment] 2022-01-20 09:10
This error is really weird: the builds on the principal branch are not failing because of this error.

I guess we have to check the agent. I'm working on this.

**Comment by dduportal** [comment] 2022-01-20 09:43
Opened https://github.com/jenkins-infra/repository-permissions-updater/pull/2326 trying to fix this.

Tested on https://github.com/jenkins-infra/repository-permissions-updater/pull/2315 (but it's sloooow to download artifacts due to JFrog outage - #2733 ).

**Comment by dduportal** [comment] 2022-01-20 09:46
Root cause is the following: while executing the pipeline instruction `tool 'jdk11'`, the following error message was thrown:

```
21:35:14  [Pipeline] tool
21:35:14  Installer "Extract *.zip/*.tar.gz" cannot be used to install "jdk11" on the node "ubuntu-20-43aa20"
21:35:14  Installer "Extract *.zip/*.tar.gz" cannot be used to install "jdk11" on the node "ubuntu-20-43aa20"
21:35:14  Installer "Extract *.zip/*.tar.gz" cannot be used to install "jdk11" on the node "ubuntu-20-43aa20"
21:35:14  Installer "Extract *.zip/*.tar.gz" cannot be used to install "jdk11" on the node "ubuntu-20-43aa20"
21:35:14  Installer "Extract *.zip/*.tar.gz" cannot be used to install "jdk11" on the node "ubuntu-20-43aa20"
```

it leds the tool in a weird state where the JAVA_HOME is not defined because tool wasn't able to complete its installation.

The PR [#2](https://github.com/jenkins-infra/repository-permissions-updater/pull/2326) explores the way of using an agent with a label `maven-11` which means "Maven installed in the PATH + a valid JDK11 installed in the path". it avoids downloading on each build.

But it's not expected to have such an error: the tool must be able to compelte its task without any issue.
Comparing with the master branch, it looks (at first glance) that only Azure VM agents are failing to execute the tool installation while EC2 VMs are working as expected.

**Comment by dduportal** [comment] 2022-01-20 10:37
I'm able to reproduce "sometime" by replaying some builds with the following minimalist pipeline:

```
node('java') {
    env.JAVA_HOME = tool 'jdk11'
    sh 'ls -l ${JAVA_HOME}'
    sh '${JAVA_HOME}/bin/java -version'
}
```

Example: https://ci.jenkins.io/job/Infra/job/jenkins-infra/job/production/731/console

=> Now to identify what "kind" of agent is started that leads to this error

**Comment by MarkEWaite** [comment] 2022-01-25 16:03
This will be resolved when https://github.com/jenkins-infra/update-center2/pull/568 is merged

**Comment by MarkEWaite** [comment] 2022-01-25 16:04
Will be resolved when https://github.com/jenkins-infra/repository-permissions-updater/pull/2334 is merged

**Comment by timja** [comment] 2022-01-25 16:18
This is currently working but not really ideal, as mark found before we can't force the java version to be 11 because of the trusted ci config.

I'm not sure what you mean by `good first issue` @MarkEWaite is that for someone on the infra team? not the easiest to solve imo.

**Comment by dduportal** [comment] 2022-01-25 18:54
Wdyt about adding the labels maven-11 (at least) on trusted ? Since jdk11 is the default in the VM templates, that should work very well ?

**Comment by timja** [comment] 2022-01-25 19:12
Yeah sure

**Comment by dduportal** [comment] 2022-01-27 17:23
PR opened to support the `maven-11` use case.

I'm not sure about the `maven` (e.g. maven + JDK8)  or `maven17` as I wasn't able to find any feature on the azure agent template configuration to override PATH and JAVA_HOME on these agent (I would have added another linux azure VM template fort each JDK version other than 11 - cc @timja if you have already see this ?).

Maybe we could add AWS EC2 templates to trusted.ci:

- More resilient (if Azure breaks or if we reach azure quotas)
- Would allow to have jdk8 an jdk17 builds.

WDYT?

**Comment by timja** [comment] 2022-01-27 17:48
yeah worth adding ec2 for more resilience i'd say.

but for now we just need java 11

**Closed** 2022-01-27 20:51 UTC
Labels: ci.jenkins.io, site:ci.jenkins.io
