### ISSUE TITLE
releases of workflow-basic-steps fails with "401 Unauthorized"

### ISSUE THREAD

**Issue by car-roll** [jenkins-infra/helpdesk#2772] opened 2022-02-07 18:59 UTC
### Service

ci.jenkins.io

### Summary

cd fails in `workflow-basic-steps` with "401 Unauthorized"

https://github.com/jenkinsci/workflow-basic-steps-plugin/runs/5097911132?check_suite_focus=true

**Comment by timja** [comment] 2022-02-07 20:23
Duplicate of https://github.com/jenkins-infra/helpdesk/issues/2771

**Closed by timja** 2022-02-07 20:23 UTC
Labels: triage
