### ISSUE TITLE
Older Debian package availability is incorrect on get.jenkins.io

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#4330] opened 2024-10-04 11:52 UTC
### Service(s)

get.jenkins.io

### Summary

The mirrorlist reported for older Debian packages incorrectly shows mirrors have the package when many do not have it.  Originally reported on [community.jenkins.io](https://community.jenkins.io/t/cant-download-jenkins-2-426-all-deb-due-to-404/21350).

For example, Jenkins 2.423 is a weekly release from 13 months ago.  The [mirrorlist page](https://get.jenkins.io/debian/jenkins_2.423_all.deb?mirrorlist) for that release looks like this:

![screencapture-get-jenkins-io-debian-jenkins-2-423-all-deb-2024-10-04-05_46_12-edit](https://github.com/user-attachments/assets/4263bf71-3690-498e-8b25-0550af38e2bf)

However, when I click the link for a mirror that is listed (like the [xmission link](https://mirror.xmission.com/jenkins/debian/jenkins_2.423_all.deb) or the [belnet link](https://ftp.belnet.be/mirror/jenkins/debian/jenkins_2.423_all.deb)), an HTTP 404 page is reported.

The mirror list for that weekly release is correctly showing that the OSU OSL mirrors ([chi](https://ftp-chi.osuosl.org/pub/jenkins/debian/jenkins_2.423_all.deb) and [nyc](https://ftp-nyc.osuosl.org/pub/jenkins/debian/jenkins_2.479_all.deb)) do **not** include those older versions.

The mirrorlist page seems to be correct for the OSU OSL mirrors and for the Servana mirror, but incorrect for the other mirrors.

### Reproduction steps

1. Open https://get.jenkins.io/debian/jenkins_2.423_all.deb?mirrorlist and see that mirrors are listed as available, but when one of the mirror links is clicked (like Belnet or xmission), it will report a 404 page not found

**Comment by dduportal** [comment] 2024-10-15 16:30
This issue is an unexpected behavior of the Redis database migration in https://github.com/jenkins-infra/helpdesk/issues/4259.
=> we should have not migrated but started from an empty database.


As discussed during the infra weekly team meeting of the 15 Oct. 2024, we need to perform an operation to fix this problem with the following steps:

1. Empty the Redis database of get.jenkins.io and restart the pods (to avoid crashes)
2. Add back the mirrors from our RUNBOOKs
3. Trigger a full mirror scan

The fallback (e.g. archives.jenkins.io) will be used during the operation. We should not have any outage for end users **however** we'll have to communicate to the user/dev/infra mailings lists, along with status.jenkins.io.

**Comment by dduportal** [comment] 2024-10-15 16:30
Proposed planning: Wednesday 16 October, morning (EU time).

**Comment by dduportal** [comment] 2024-10-16 11:47
Announcing the operation:

- status.jenkins.io (ref. https://github.com/jenkins-infra/status/pull/546)
- Mailing lists (users, dev and infra): https://groups.google.com/g/jenkinsci-dev/c/J-jayVlbBb4
- Elements messages thread: https://matrix.to/#/!JLUOInpEYmxJIYXlzs:matrix.org/$33XwZJpdpYO0i18E2fJGtfhjSpqZhhT_fY6nZiMtLhw?via=g4v.dev&via=gitter.im&via=matrix.org

**Comment by dduportal** [comment] 2024-10-16 11:51
Let's increase the size of the archives.jenkins.io server ([currently 2 vCPUS and 2 Gb](https://github.com/jenkins-infra/digitalocean/blob/eecd0fc04506d55460dc61ac2a842937dbcfbc37/archives.jenkins.io.tf#L23C18-L23C29)) to ensure we can handle the upcoming load: 

- Ensure packages (and kernel) are up to date
- Taking snapshots of the droplet (live + cold once stopped)
- Stopping the droplet to snapshot + resize

**Comment by dduportal** [comment] 2024-10-16 12:11
> Let's increase the size of the archives.jenkins.io server ([currently 2 vCPUS and 2 Gb](https://github.com/jenkins-infra/digitalocean/blob/eecd0fc04506d55460dc61ac2a842937dbcfbc37/archives.jenkins.io.tf#L23C18-L23C29)) to ensure we can handle the upcoming load:
> 
>     * Ensure packages (and kernel) are up to date
> 
>     * Taking snapshots of the droplet (live + cold once stopped)
> 
>     * Stopping the droplet to snapshot + resize

Done ! Notes:

- The terraform job is failing. As such I disabled it in infra.ci and did the upgrade manually.
TODO: adapt the terraform project and fix it later

- The new size is 4 vCPUS and 8 Gb with Basic Intel:

<img width="1039" alt="Capture d’écran 2024-10-16 à 13 54 45" src="https://github.com/user-attachments/assets/848bca18-6dd9-470b-ac54-fdd39eba3152">

**Comment by dduportal** [comment] 2024-10-16 12:14
Performed one last backup of the mirrors for get.jenkins.io in https://github.com/jenkins-infra/runbooks/commit/336599ee03c4f48b411f6a371a75bde518b86237 (both command lines to add mirrors + export of the YAML advanced configuration).

Note: need to do the same for azure.updates.jenkins.io as the instance is co-located!

**Comment by dduportal** [comment] 2024-10-16 12:54
Redis data flushed: all mirrorbits instances are cleaned out:

<img width="791" alt="Capture d’écran 2024-10-16 à 14 23 55" src="https://github.com/user-attachments/assets/c08e477e-b566-4fb1-b37b-29a289f63282">

<img width="1606" alt="Capture d’écran 2024-10-16 à 14 44 40" src="https://github.com/user-attachments/assets/d904a74e-2a68-46ca-af80-a1cc15adf624">


archives.jenkins.io works as fallback as expected. We see an increased activity: the old size (2 CPU / 2 Gb) would have handled the load, but given how cheap it is, let's stay with the new sizing:

<img width="1004" alt="Capture d’écran 2024-10-16 à 14 43 33" src="https://github.com/user-attachments/assets/a7bb271d-e81f-4fb3-afbe-3e096d8a2315">

Persisting the new size: https://github.com/jenkins-infra/digitalocean/pull/207

**Comment by dduportal** [comment] 2024-10-16 13:11
- All mirrorbits instances are currently:
  - Using their fallbacks
  - Scanning their filesystem (initial), adding 1 entry per file in their respective Redis instances => should take 1 to 2 hours

Also, the OSUOSL mirror (NYC) has been added back to get.jenkins.io. Let's wait for the scan to be processed.


In parallel: setting back the mirrors.updates.jenkins HTTP and HTTPS instances

**Comment by dduportal** [comment] 2024-10-16 13:34
Update:
- mirrors on mirrors.updates.jenkins.io are back in shape.
- get.jenkins.io is still scanning its filesystem. WAR and packages have been covered, it is checking all plugins (letter C has been reached). I would not want to be a SSD cell of this file share right now...

**Comment by dduportal** [comment] 2024-10-16 15:28
Update:

- Initial file system scan finished with success. It was 2 hours long, the limiting resource was the pods memory, closely followed by pods CPU (throttled due to pod limits). The file system was solicited but still plenty of available resources on its side:

<img width="1572" alt="Capture d’écran 2024-10-16 à 16 03 51" src="https://github.com/user-attachments/assets/52c61036-1c3a-4689-b7f9-626ed1f34aa9">
<img width="1546" alt="Capture d’écran 2024-10-16 à 16 50 39" src="https://github.com/user-attachments/assets/90a00c58-41fc-4f2f-ac8b-b6504b9b079d">
<img width="1542" alt="Capture d’écran 2024-10-16 à 16 50 48" src="https://github.com/user-attachments/assets/109016c8-c09e-4a81-ad7f-edef335344cf">

- Starting again to add back mirrors one by one

**Comment by dduportal** [comment] 2024-10-16 16:06
Update:

- Mirrors are being added back with success and already started handling traffic.
- The error `UTC HTTP error: write tcp xxxxx:8080->yyyyyyy:53154: write: broken pipe
YYYY/MM/DD HH:mm:ss http: superfluous response.WriteHeader call from github.com/etix/mirrorbits/http.(*HTTP).mirrorStatsHandler (http.go:607)` has been located: it appears when adding more than 12 mirrors in `mirrorbits`.
- Updated the mirrors config as there were mistakes + removed FTP urls if there are already rsync available (faster)

**Comment by dduportal** [comment] 2024-10-16 16:20
- All mirrors added back. Some are still being scanned and marked as offline: https://get.jenkins.io/windows/2.481/jenkins.msi?mirrorlist
- The initial problem is gone: https://get.jenkins.io/debian/jenkins_2.423_all.deb?mirrorlist shows only 2 mirrors (which have the file) and the fallback as expected.

**Closed by dduportal** 2024-10-16 16:20 UTC
Labels: get.jenkins.io
