### ISSUE TITLE
Feature Request: auto create a status.jenkins.io issue from an helpdesk's issue with Label

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#2988] opened 2022-06-14 15:24 UTC
Would be great to be able to spawn a new issue within status.jenkins.io from github by submitting an issue in the helpdesk repository with a specific label (create_status_issue for example) .
With the text content from the helpdesk issue and a link to it.

**Comment by lemeurherve** [comment] 2022-06-14 15:37
Duplicate of https://github.com/jenkins-infra/helpdesk/issues/2564 😉 
I'll add the label feature to the existing ticket.

**Closed by lemeurherve** 2022-06-14 15:37 UTC
Labels: helpdesk, status.jenkins.io
