### ISSUE TITLE
Artifact caching proxy repo.do.jenkins.io is not answering requests from bom build

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3889] opened 2024-01-06 11:54 UTC
### Service(s)

Artifact-caching-proxy

### Summary

The master branch of the plugin bill of materials fails the build after about 15 minutes with a report that it could not download a jar file.

### Reproduction steps

1. Open https://ci.jenkins.io/job/Tools/job/bom/job/master/2383/console and see the [log message](https://ci.jenkins.io/job/Tools/job/bom/job/master/2383/console#:~:text=04%3A42%3A12%20%20%5BINFO%5D%20%2D%2D%2D%20spotless,java.io.IOException%3A%20Failed%20to) that says:

```
04:42:12  [INFO] --- spotless:2.41.1:check (default) @ parent ---
04:42:25  [WARNING] Could not validate integrity of download from https://repo.do.jenkins.io/public/com/squareup/okio/okio-jvm/3.2.0/okio-jvm-3.2.0.jar
04:42:25  org.eclipse.aether.transfer.ChecksumFailureException: Checksum validation failed, no checksums available
04:42:25      at org.eclipse.aether.internal.impl.AbstractChecksumPolicy.onNoMoreChecksums (AbstractChecksumPolicy.java:63)
04:42:25      at org.eclipse.aether.connector.basic.ChecksumValidator.validate (ChecksumValidator.java:112)
04:42:25      at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask (BasicRepositoryConnector.java:484)
04:42:25      at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:414)
04:42:25      at org.eclipse.aether.util.concurrency.RunnableErrorForwarder.lambda$wrap$0 (RunnableErrorForwarder.java:66)
04:42:25      at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1144)
04:42:25      at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:642)
04:42:25      at java.lang.Thread.run (Thread.java:1583)
04:42:38  [INFO] ------------------------------------------------------------------------
04:42:38  [INFO] Reactor Summary for parent 2700.v6ff62ffe90e2:
04:42:38  [INFO] 
04:42:38  [INFO] parent ............................................. FAILURE [05:35 min]
04:42:38  [INFO] bom-weekly ......................................... SKIPPED
04:42:38  [INFO] bom-2.426.x ........................................ SKIPPED
04:42:38  [INFO] bom-2.414.x ........................................ SKIPPED
04:42:38  [INFO] bom-2.401.x ........................................ SKIPPED
04:42:38  [INFO] sample ............................................. SKIPPED
04:42:38  [INFO] ------------------------------------------------------------------------
04:42:38  [INFO] BUILD FAILURE
04:42:38  [INFO] ------------------------------------------------------------------------
04:42:38  [INFO] Total time:  09:04 min
04:42:38  [INFO] Finished at: 2024-01-06T11:42:38Z
04:42:38  [INFO] ------------------------------------------------------------------------
04:42:38  [ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.41.1:check (default) on project parent: Execution default of goal com.diffplug.spotless:spotless-maven-plugin:2.41.1:check failed: java.io.IOException: Failed to 
```

**Comment by MarkEWaite** [comment] 2024-01-06 14:33
Resolved by changes from @dduportal .  Thanks!

**Comment by dduportal** [comment] 2024-01-08 08:52
This issue is caused by https://github.com/jenkins-infra/helpdesk/issues/3842 where we forgot to clean-up the ACP cache.

Artifacts which used to be stored in repo.jenkins-ci.org and should be now served by Apache Maven central need to be marked as decached.

Given the amount of artifacts, better to uncache the 6 ACPs.

For each of the 3 Kubernetes clusters hosting an ACP (`doks-public`, `publick8s` and `eks-public`), we ran the following commands:

```shell
# Clean up filesystem's cache
kubectl exec -n artifact-caching-proxy -ti artifact-caching-proxy-<ID> -- rm -rf /data/nginx-cache/*
# Delete pod to close file handles and clean up memory 
kubectl delete pod -n artifact-caching-proxy artifact-caching-proxy-<ID>
```

with `<ID>` being `1` then `0`.

**Closed** 2024-01-08 11:01 UTC
Labels: artifact-caching-proxy
