### ISSUE TITLE
Packaging job on ci.jenkins.io never completes - retries fail

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#4106] opened 2024-05-27 12:24 UTC
### Service(s)

ci.jenkins.io

### Summary

[Packaging job](https://ci.jenkins.io/job/Packaging/job/packaging/job/master/) on ci.jenkins.io has failed to allocate an agent for last 8 hours

### Reproduction steps

1. Open the [packaging job](https://ci.jenkins.io/job/Packaging/job/packaging/job/master/), confirm that the agent is not allocated

**Comment by dduportal** [comment] 2024-05-27 12:36
The pipeline logs shows errors like the following, indicating that the pod agents failed to be started (created in Kubernetes but never reached the "Running" state with an active connection to the controller):

```
06:17:06  ERROR: Failed to launch packaging-packaging-master-329-9hqpp-g6p96-v3n93
06:17:06  io.fabric8.kubernetes.client.KubernetesClientTimeoutException: Timed out waiting for [1000000] milliseconds for [Pod] with name:[packaging-packaging-master-329-9hqpp-g6p96-v3n93] in namespace [jenkins-agents].
06:17:06  	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.waitUntilCondition(BaseOperation.java:939)
06:17:06  	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.waitUntilReady(BaseOperation.java:921)
06:17:06  	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.waitUntilReady(BaseOperation.java:97)
06:17:06  	at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:185)
06:17:06  	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:297)
06:17:06  	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
06:17:06  	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80)
06:17:06  	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
06:17:06  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
06:17:06  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
06:17:06  	at java.base/java.lang.Thread.run(Unknown Source)
06:17:06  Pod jenkins-agents/packaging-packaging-master-329-9hqpp-g6p96-v3n93 was just deleted
```

**Comment by dduportal** [comment] 2024-05-27 12:38
FWIW, last successful build was the 10 of May 2024. Since then we've moved the [ci.jenkins.io Linux container agent workloads from AWS/DigitalOcean to Azure](https://github.com/jenkins-infra/helpdesk/issues/3954): might (or might not be related).

Currently checking the pipeline agent label and setup, along with other errors in the controller and pods.

**Comment by dduportal** [comment] 2024-05-27 12:39
Oh: this pipeline uses a custom pod template definitions: https://github.com/jenkinsci/packaging/blob/3bb91b8dcb84387f4c04497d118109f029681fe2/Jenkinsfile#L12 (https://github.com/jenkinsci/packaging/blob/master/KubernetesPod.yaml).


This is most probably broken since https://github.com/jenkins-infra/helpdesk/issues/3954. Let's see if we can reuse the "all in one container image" here (cc @smerle33 FYI)

**Comment by dduportal** [comment] 2024-05-27 12:47
Confirmed the issue: the "custom" pod template definition is missing tolerations which forbids it to be scheduled.

As it uses the `jenkinsciinfra/packaging` Docker image, using the "All in one" image might be counter-productive as this job should have the same behavior in both CI and (private) CD.

We might have to update the definition to inherit from existing pod template (to get the admin-defined parameters) and only override what is needed (at least the image).

**Comment by dduportal** [comment] 2024-05-27 17:12
PR opened in https://github.com/jenkinsci/packaging/pull/465. I can't tell if it fails because I'm not a maintainer of the repo, or if it is an issue due to my PR.

**Comment by dduportal** [comment] 2024-06-04 09:37
PR merged, agents are running

**Closed by dduportal** 2024-06-04 09:37 UTC
Labels: ci.jenkins.io
