### ISSUE TITLE
HTTP errors on multiple sites

### ISSUE THREAD

**Issue by nephre** [jenkins-infra/helpdesk#4428] opened 2024-11-28 08:50 UTC
### Service(s)

Update center

### Summary

I am experiencing multiple 404 (also seen 503) http errors on various jenkins sites:
wget https://updates.jenkins.io/download/plugins/active-directory/2.26/active-directory.hpi
https://updates.jenkins.io/project/roadmap/
https://updates.jenkins.io/blog/

**Comment by dduportal** [comment] 2024-11-28 08:56
Hi @nephre , thanks for reporting.

As described in https://status.jenkins.io/issues/2024-11-28-outage-uc/, we were facing an Azure outage which impacted the Update Center.

We will report here the root cause and fixes.

The problem should be gone: can you confirm it?

**Comment by nephre** [comment] 2024-11-28 09:17
> The problem should be gone: can you confirm it?

@dduportal Yes, I am able to download aforementioned hpi, thank you.
Roadmap link and blog still return 404, I don't know if it's related, or other issue

**Comment by dduportal** [comment] 2024-11-29 13:51
> > The problem should be gone: can you confirm it?
> 
> @dduportal Yes, I am able to download aforementioned hpi, thank you. Roadmap link and blog still return 404, I don't know if it's related, or other issue

Thanks @nephre ! The last 404 you had yesterday were most probably due to Fastly decaching. It was fixed yesterday ~15 min after your comment.

We've worked on https://github.com/jenkins-infra/helpdesk/issues/4402 and we see way better results on the Update Center. We'll see in a few days!

Closing the issue as the outage is finished since 10:30 UTC the 28/11

**Closed by dduportal** 2024-11-29 13:51 UTC
Labels: updateCenter
