### ISSUE TITLE
Windows ACI 11 agent broken: no `git` found

### ISSUE THREAD

**Issue by jglick** [jenkins-infra/helpdesk#3189] opened 2022-10-19 15:39 UTC
### Service(s)

ci.jenkins.io

### Summary

```
>git config --global core.longpaths true 
 'git' is not recognized as an internal or external command,
 operable program or batch file.
```

### Reproduction steps

Just tried to rebuild after ci.jenkins.io came back up; still broken: https://ci.jenkins.io/job/Plugins/job/workflow-job-plugin/job/PR-303/5/execution/node/51/log/

**Comment by dduportal** [comment] 2022-10-19 15:48
Root cause is me: https://github.com/jenkins-infra/docker-inbound-agents/pull/36 but it is weird though because I expect https://github.com/jenkins-infra/docker-inbound-agents/blob/main/maven/jdk11/Dockerfile.nanoserver#L3 to have `git. Gotta check if the upstream image isn't broken.

**Comment by dduportal** [comment] 2022-10-19 15:53
Mmmh:
- https://github.com/jenkinsci/docker-inbound-agent/blob/62ee56932623a0a66179b0130da806c39d5c323f/11/windows/nanoserver-1809/Dockerfile => no git installation as expected (it is a specialization of the parent image)
- but https://github.com/jenkinsci/docker-agent/blob/master/11/windows/nanoserver-1809/Dockerfile#L43-L50 installs `git` 

There is something fishy

**Comment by jglick** [comment] 2022-10-19 15:59
I guess `docker-inbound-agents` needs some smoke tests?

**Comment by dduportal** [comment] 2022-10-19 16:13
> I guess `docker-inbound-agents` needs some smoke tests?

absolutely

**Comment by dduportal** [comment] 2022-10-19 17:19
- Fix applied to both JDK8 and JDK11
- New images built and published

=> retrying the build to validate

**Comment by dduportal** [comment] 2022-10-19 17:42
For the smoke test: https://github.com/GoogleContainerTools/container-structure-test#command-tests

**Comment by dduportal** [comment] 2022-10-19 17:49
https://ci.jenkins.io/job/Plugins/job/workflow-job-plugin/job/PR-303/6/ => successfull.

@jglick @daniel-beck sorry for the inconvenience. We'll close this issue once a non-regression test will be provided to these agents (at least on some basics elements)

**Comment by dduportal** [comment] 2022-10-25 15:42
@smerle33 the next step is the following:

- The pipeline https://github.com/jenkins-infra/docker-inbound-agents/blob/main/Jenkinsfile_k8s which builds the Docker images for ACI (2 targets: Maven Windows JDK8 and Maven Windows JDK11) invokes the `buildDockerAndPublishImage()` pipeline library function for each image.
- This pipeline library function allows smoke testing of the images if test harness with the correct naming (and correct tooling) are found: https://github.com/jenkins-infra/pipeline-library/blob/master/vars/buildDockerAndPublishImage.groovy#L148-L152 specifies that any `cst-windows.yml` found within the `imageDir` directory.
  - You have to specify the `imageDir` attribute for each call to the pipeline library function first (otherwsie the default value  `.` points to the repository root). For instance `imageDir: 'maven/8/` for Windows Maven 8.
  - Then you can create one `cst-windows.yml` file for each directory (`maven/8/cst-windows.yml`) for instance
- These "cst*.yml" files are test harness definitions for https://github.com/GoogleContainerTools/container-structure-test  (installed on both Linux and Windows VMs).
  - We want to use the feature https://github.com/GoogleContainerTools/container-structure-test#command-tests to specify a set of command to be run on each freshly built image to smoke test: `git version`, `mvn -v` (start with these two as a first step).

**Comment by dduportal** [comment] 2022-10-31 19:08
https://github.com/jenkins-infra/docker-inbound-agents/pull/42

**Closed** 2022-10-31 19:45 UTC
Labels: ci.jenkins.io
