### ISSUE TITLE
Upgrade Windows docker agents to 2022

### ISSUE THREAD

**Issue by slide** [jenkins-infra/helpdesk#3142] opened 2022-09-21 03:43 UTC
### Service(s)

ci.jenkins.io

### Summary

The current Windows docker agents on ci.jenkins.io are based on Windows 2019, which means we can't build images for 2022. It would be good to upgrade the docker agents to use a 2022 base image so we can build 2022 images.

**Comment by timja** [comment] 2022-09-21 06:54
Duplicate of https://github.com/jenkins-infra/helpdesk/issues/2629?

**Comment by dduportal** [comment] 2022-09-21 10:39
Absolutely, closing as duplicate.

**Closed by dduportal** 2022-09-21 10:39 UTC
Labels: triage, ci.jenkins.io
