### ISSUE TITLE
[BUG] Missing "Report an issue with this plugin" option in 'Mina SSHD API' plugin

### ISSUE THREAD

**Issue by Viveksati5143** [jenkins-infra/helpdesk#3785] opened 2023-10-15 21:10 UTC
### Service(s)

plugins.jenkins.io

### Summary

As visible in the screenshot - "Report an issue with this plugin" option is missing in 'Mina SSHD API' plugins which needs to be added like other plugins!!!

![image](https://github.com/jenkins-infra/helpdesk/assets/100852245/14e8737b-80a2-4a17-82d0-22e0bbb01dbe)

### Reproduction steps

- Go to Jenkins Plugins
-  Search for Mina SSHD Api Plugin 
- See missing report option

**Comment by Viveksati5143** [comment] 2023-10-15 21:10
I would like to work on this issue

**Comment by MarkEWaite** [comment] 2023-10-16 21:24
@Viveksati5143 unfortunately, the solution to this one is much more complicated than you might have expected.

This is a duplicate of https://github.com/jenkins-infra/repository-permissions-updater/issues/2911

**Closed by MarkEWaite** 2023-10-16 21:24 UTC
Labels: triage, plugins.jenkins.io
