### ISSUE TITLE
Update center job is failing

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3411] opened 2023-02-26 22:15 UTC
### Service(s)

trusted.ci.jenkins.io

### Summary

The update center job is failing since build 710789:
```
22:51:00 ModuleNotFoundError: No module named 'blobxfer_cli'
```

**Comment by dduportal** [comment] 2023-02-27 09:25
Jenkins Infra team is currently debugging. So far, it's the line https://github.com/jenkins-infra/update-center2/blob/22fc759f225ac53d95f88320914eb60b40f7e62d/site/publish.sh#L20 which fails since ~11h.

We are investigating the VM updates.jenkins.io, focusing on the `blobxfer` CLI.

**Comment by dduportal** [comment] 2023-02-27 10:10
We identified the error and are working on fixing it. ETA: next hour.

**Comment by smerle33** [comment] 2023-02-27 10:23
- fixed applied in https://github.com/jenkins-infra/mirror-scripts/pull/10
- checked that update center job is working again
- replayed the update center job with a 14 hours time window

**Comment by smerle33** [comment] 2023-02-27 10:26
update center job back to the initial value of 6 hours time windows

**Comment by smerle33** [comment] 2023-02-27 10:32
> I suppose this is also why https://updates.jenkins.io/download/plugins/pipeline-graph-view/161.v4e3820f16486/pipeline-graph-view.hpi and subsequent releases respond with "Not Found". But that was released at 2023-02-25T17:54:48Z, i.e. 40 hours ago rather than just 11.

<img width="1360" alt="Capture d’écran 2023-02-27 à 11 31 34" src="https://user-images.githubusercontent.com/95630726/221540231-24eeacda-6dec-45a2-ba10-96094bb8ca03.png">

the version 163.v84cf2343b_266  is now available, we are checking into older missing versions.

**Comment by smerle33** [comment] 2023-02-27 10:48
> I suppose this is also why https://updates.jenkins.io/download/plugins/pipeline-graph-view/161.v4e3820f16486/pipeline-graph-view.hpi and subsequent releases respond with "Not Found". But that was released at 2023-02-25T17:54:48Z, i.e. 40 hours ago rather than just 11.

we did replay the job with a bigger time windows and now, all the versions are available in the updates.jenkins.io download sections.

**Comment by dduportal** [comment] 2023-02-27 13:43
Post mortem: it seems that the issue was caused by https://github.com/jenkins-infra/jenkins-infra/pull/2659 .

The `blobxfer` command line was installed manually on pkg.jenkins.io (the VM which also hosts the service updates.jenkins.io) and not tracked by the Puppet configuration system.

It was installed using `python2.7` as per:

```
$ python2.7 -m pip list 
# ...
blobxfer (1.6.0)
```

Since blobxfer installed with python3.8 conflicts with certbot 1.x (due to some incompatible cryptography dependencies), we decided to setup a Python virtual env to fix the trusted.ci's index deployementy for now (ref. https://github.com/jenkins-infra/mirror-scripts/pull/10).

Next steps:

- [ ] Search if there are other blobxfer calls on the infrastructrure and switch all of them to a Python virtual env
- [ ] Track the packages and virtual env setup on the VM updates.jenkins.io (to ensure blobxfer is tracked and maintained by puppet (which also helps for https://github.com/jenkins-infra/helpdesk/issues/2649)
- [ ] Upgrade blobxfer from `1.6.0` to latest `1.11.0` (from September 2021) to benfits from performance fixes


Long term: replace blobxfer (which has not been updated since sept. 2021) as per https://github.com/jenkins-infra/helpdesk/issues/3414

**Comment by dduportal** [comment] 2023-02-27 15:55
- https://github.com/jenkins-infra/mirror-scripts/pull/11 to use the virtual env on all the call to `blobxfer` in the jenkins-infra/mirror-scripts repository.

**Comment by dduportal** [comment] 2023-03-24 17:39
Tracked the blobxfer installation in https://github.com/jenkins-infra/jenkins-infra/pull/2710 for the pkg VM

**Comment by dduportal** [comment] 2023-03-24 17:41
Final steps before closing:

- [ ] Ensure that an update of the `requirements.txt` in https://github.com/jenkins-infra/mirror-scripts/blob/master/requirements.txt will trigger a new puppet run (as the code in https://github.com/jenkins-infra/jenkins-infra/pull/2710 does not goes in that level of details)
- [ ] Bump blobxfer in https://github.com/jenkins-infra/mirror-scripts/blob/master/requirements.txt to 1.11.0

**Comment by dduportal** [comment] 2023-03-24 19:32
https://github.com/jenkins-infra/jenkins-infra/pull/2717 + https://github.com/jenkins-infra/jenkins-infra/commit/dbf519dc45d0456f4bb2b3934109af4fe7a71a45 for version check

**Closed** 2023-03-24 19:46 UTC
Labels: trusted.ci.jenkins.io, blobxfer
