### ISSUE TITLE
unbale to install the jenkins plugin name Role-based Authorization StrategyVersion 689.v731678c3e0eb_

### ISSUE THREAD

**Issue by CSPPravin** [jenkins-infra/helpdesk#3953] opened 2024-02-15 19:30 UTC
### Service(s)

jenkins.io

### Summary

Role-based Authorization StrategyVersion
689.v731678c3e0eb_ not install

```[tasklist]
### Tasks
```

**Comment by MarkEWaite** [comment] 2024-02-15 19:31
Not likely related to Jenkins infra

**Comment by MarkEWaite** [comment] 2024-02-15 19:32
Without steps to duplicate the issue, we will close Ross

**Comment by CSPPravin** [comment] 2024-02-15 19:35
how can we handel it

**Comment by MarkEWaite** [comment] 2024-02-15 19:40
You have not given enough description for anyone to decide if the issue is specific to your environment or a general issue. When you do not provide enough information, you reduce the chance that others will help you. 

In this case, it is most likely a local issue that the infra fan cannot help

**Comment by dduportal** [comment] 2024-02-16 16:44
Closing as it is unrelated to the Jenkins infrastructure. If you need help do not hesitate to reach community.jenkins.io to have the whole community to help!

**Closed by dduportal** 2024-02-16 16:43 UTC
Labels: jenkins.io
