### ISSUE TITLE
trusted.ci doesn't spawn new nodes

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3416] opened 2023-02-27 22:08 UTC
### Service(s)

trusted.ci.jenkins.io

### Summary

Builds are queued for ~4h currently because no linux, docker, docker-windows or maven-11 nodes are available.

**Comment by dduportal** [comment] 2023-02-28 07:10
- Unblocked by generating manually a new client secret
- Caught the error: I misled @smerle33 yesterday by indicating to use an `azuread_application_password` in https://github.com/jenkins-infra/azure/blob/3dc705fb66e01984c2ea1672a82fbdb3a3c29904/trusted.ci.jenkins.io.tf#L27 while a https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/service_principal_password was expected by the Jenkins Azure AD plugin (cc @timja could you confirm the former is not supported ?).
The manual generation is a SP password.

**Comment by dduportal** [comment] 2023-02-28 07:22
- Note: it seems the Azure client has some cache, EVEN when the password is changed and this cache is used by the "Verify" buttons. Sounds like a bug to me (just reproduced the behavior by setting an incorrect password and verifying). 
=> For the infra team: we must fully "Save + Reload configuration from file", or ideally restart the controller to ensure the credential is correct :|
- Builds are flowing with the temporary SP password (`trusted.ci.jenkins.io-20230228`)
- https://github.com/jenkins-infra/azure/pull/281 to add a new SP password, managed as expected by terraform

**Comment by dduportal** [comment] 2023-02-28 07:40
https://github.com/jenkins-infra/azure/pull/281 is merged, but the main build fails with the error "insufficient privileges". It seems that the terraform_app SP for production lacks a permission to allow creating "Client secrets". Worth checking (no emergency : this issue is unblocked due to a temp client secret valid for 1 year).

**Comment by timja** [comment] 2023-02-28 07:45
> Note: it seems the Azure client has some cache, EVEN when the password is changed and this cache is used by the "Verify" buttons. Sounds like a bug to me (just reproduced the behavior by setting an incorrect password and verifying)

Hmm might be this line:
https://github.com/jenkinsci/azure-vm-agents-plugin/blob/45d024f0b71e2729bcc5ddfd22d3122cd7e0ee9c/src/main/java/com/microsoft/azure/vmagent/AzureVMCloud.java#L1031-L1033

It will have been cleared from the cache:
https://github.com/jenkinsci/azure-credentials-plugin/blob/ca636e74b997d4f77674c1efe788d0713a2cee0c/src/main/java/com/microsoft/azure/util/AzureCredentials.java#L470. 

but may still be holding a reference.
(saving the cloud config page may fix it)

**Comment by timja** [comment] 2023-02-28 07:45
> Application.ReadWrite.All

This is the lower permission

**Comment by dduportal** [comment] 2023-02-28 07:55
Thanks @timja !

**Comment by dduportal** [comment] 2023-02-28 08:04
> > Application.ReadWrite.All
> 
> This is the lower permission

I understand, from https://learn.microsoft.com/en-us/graph/permissions-reference#remarks-3, that we should use the `Application.ReadWrite.OwnedBy` permission for this case, does it make sense?

**Comment by timja** [comment] 2023-02-28 08:05
Yes looks like it will work for that

**Comment by dduportal** [comment] 2023-02-28 14:18
Next steps before closing this issue:

- Add the correct permission to the service principal used by jenkins-infra/azure's terraform project (⚠️ different than the azure-net which is used for LetsEncrypt/DNS permissions) to unblock the builds of this project (currently failing with 403 error)
  - Should be a role with `Application.ReadWrite.OwnedBy` 
  - Once the build is fixed, a new "Client Secret" named `trusted.ci.jenkins.io-managed` should appear in the Azure Portal, in the `trusted.ci.jenkins.io` Azure AD application
- From a contributor machine, retrieve the secret from the terraform state and replace the current secret into trusted.ci.jenkins.io credentials
  - From a local machine with `az login` run as Azure Admin, run the `make -C ./.shared-tools/terraform/  validate && terraform show -json` command to see the terraform state. Search for the `azure_serviceprincipal_paswword`'s `value` attribute.
   - Only change the "service principal password" in the trusted.ci credentials, save and verify again
- Remove the "temporary" credentials that I creadted manually from the Azure portal (name: `trusted.ci.jenkins.io-20230228`)
- Restart the controller before starting a new build (javadoc for instance) to verify that the new secret works

**Comment by dduportal** [comment] 2023-03-08 20:09
OK, did spent some time on this and it looked solved 🥳 

- https://github.com/jenkins-infra/azure/pull/285 and https://github.com/jenkins-infra/azure/pull/286 ensured that the `terraform-production` service principal is the explicit owner of both the App and the `trusted.ci.jenkins.io` SP as per https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/service_principal#api-permissions
- An admin had to manually grant consent for the API permissions for the `terraform-production` SP and its app. This step is *required* , *manual* and to be done only one time. it's now checked:

![Capture d’écran 2023-03-08 à 20 33 41](https://user-images.githubusercontent.com/1522731/223835647-1a601cb6-7fab-4324-87e3-e67b07c1387d.png)

=> after this, the 403 error when creating a SP password was gone

- In order to view the "Client secret" from the Azure Portal UI (with its rotation date) to benefit from the UI alerts when "almost expired", I had to switch back from a Service Principal password to an Application password in https://github.com/jenkins-infra/azure/commit/2958636d5e76813a6c15c95c415e4fd55d62ff4d
  - We thought it was not working with the Jenkins Azure VM plugin initially,; but it was because we clearly messed up the credential update. Tested with a removal of former secret + full trusted.ci restart and it works

![Capture d’écran 2023-03-08 à 21 07 18](https://user-images.githubusercontent.com/1522731/223836922-da0c113b-1cb5-4787-a725-96c9c1000c10.png)

  - Also removed the "time_rotation" resource as it was granting a 2-years validity when specified 365 days 🤦 . The explicit `end_date` attribute is easier to read/parse

**Closed** 2023-03-08 20:14 UTC
Labels: trusted.ci.jenkins.io

**Comment by dduportal** [comment] 2023-03-09 11:36
One last mile: https://github.com/jenkins-infra/azure/pull/287
