### ISSUE TITLE
Branch strategy on ci.jenkins.io diverges from prior configuration

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3650] opened 2023-07-05 11:05 UTC
### Service(s)

ci.jenkins.io

### Summary

The previous configuration aborted branch builds, once a PR has been created (e.g., dependabot/renovate, or when working directly on the repository). That's no longer the case. Currently, if you create an upstream branch and a PR, both are built, doubling the prior workload.

**Comment by dduportal** [comment] 2023-07-05 11:09
Caused by the operation in https://github.com/jenkins-infra/helpdesk/issues/3535

**Comment by dduportal** [comment] 2023-07-05 13:44
For the https://ci.jenkins.io/job/Core/ organization scanning, applying the following change (will trigger and indexation):

- Exclude archived repositories
- Orphaned Item Strategy 
  -> Enable Abort builds
  -> Discard old items (no max day, no max items)

**Comment by dduportal** [comment] 2023-07-05 13:52
> For the https://ci.jenkins.io/job/Core/ organization scanning, applying the following change (will trigger and indexation):
> 
>     * Exclude archived repositories
> 
>     * Orphaned Item Strategy
>       -> Enable Abort builds
>       -> Discard old items (no max day, no max items)

Applied recursively, the "Abort build" option is now present on each.

**Comment by NotMyFault** [comment] 2023-07-05 13:55
> NotMyFault for which job(s) do you see this behavior?

I did a quick demo earlier with https://github.com/jenkinsci/console-column-plugin/pull/123:
![Screenshot 2023-07-05 at 15 53 55](https://github.com/jenkins-infra/helpdesk/assets/13383509/9c99153e-737f-48a9-8fb4-3a4778a44ab0)
The couple of checks weren't there before the update.



> For the https://ci.jenkins.io/job/Core/ organization scanning, applying the following change (will trigger and indexation):
> 
> * Exclude archived repositories

Shouldn't that be applied to every folder? We don't really need to index archived repositories anywhere.

**Comment by dduportal** [comment] 2023-07-05 14:02
For the https://ci.jenkins.io/job/Plugins/ organization scanning, applying the following change (will trigger an indexation):

- Exclude archived repositories
- Orphaned Item Strategy 
  -> Enable Abort builds
  -> Discard old items (no max day, no max items)

**Comment by dduportal** [comment] 2023-07-05 14:04
> I did a quick demo earlier with [jenkinsci/console-column-plugin#123](https://github.com/jenkinsci/console-column-plugin/pull/123): ![Screenshot 2023-07-05 at 15 53 55](https://user-images.githubusercontent.com/13383509/251172077-9c99153e-737f-48a9-8fb4-3a4778a44ab0.png) The couple of checks weren't there before the update, coming from https://ci.jenkins.io/job/Plugins/job/console-column-plugin/job/yoho/2/, which built the branch separately to the PR.


Thanks! Applying to the "Plugins" org scanning (https://github.com/jenkins-infra/helpdesk/issues/3650#issuecomment-1621825160). Brace youselves.


> > 
> > * Exclude archived repositories
> 
> Shouldn't that be applied to every folder? We don't really need to index archived repositories anywhere.

100% agree with you. Worth working on https://github.com/jenkins-infra/helpdesk/issues/3071

**Comment by dduportal** [comment] 2023-07-05 16:16
> For the https://ci.jenkins.io/job/Plugins/ organization scanning, applying the following change (will trigger an indexation):
> 
>     * Exclude archived repositories
> 
>     * Orphaned Item Strategy
>       -> Enable Abort builds
>       -> Discard old items (no max day, no max items)

Ran with success (and only 1 rate limit). Result:

```
Evaluating orphaned items in Plugins
Will remove testproject-plugin
Will remove icon-shim-plugin
Will remove azure-commons-plugin
Will remove analysis-test-plugin
Will remove android-lint-plugin
Will remove custom-view-tabs-plugin
Will remove suppress-stack-trace-plugin
Will remove aribot-plugin
Will remove blueocean-executor-info-plugin
Will remove osf-builder-suite-xml-linter-plugin
Will remove analysis-core-plugin
Will remove pipeline-leo-deploy-step-plugin
Will remove dry-plugin
Will remove warnings-plugin
Will remove evergreen-plugin
Will remove stride-notification-plugin
Will remove findbugs-plugin
Will remove analysis-collector-plugin
Will remove fabric-beta-publisher-plugin
Will remove checkstyle-plugin
Will remove lambda-test-runner-plugin
Will remove tasks-plugin
Will remove pmd-plugin
Will remove remoting-security-workaround-plugin
Will remove headspin-plugin
Will remove ruby-runtime-plugin
Will remove google-container-security-plugin
Will remove coding-webhook-plugin
Will remove lightstep-incident-response-plugin
Will remove maven-hudson-dev-plugin
Will remove qualys-api-security-plugin
Will remove fortify-cloudscan-plugin
Will remove popper-api-plugin
Finished: SUCCESS
```

**Comment by dduportal** [comment] 2023-07-05 16:27
For the https://ci.jenkins.io/job/Infra organization scanning, applying the following change (will trigger an indexation):

* Remove `awestruct-ibeams`
* Scan Organization Triggers  set to 1day (instead of 1 week)
* Orphaned Item Strategy
  -> Enable Abort builds
  -> Discard old items (no max day, no max items)

**Comment by dduportal** [comment] 2023-07-05 16:27
> For the https://ci.jenkins.io/job/Infra organization scanning, applying the following change (will trigger an indexation):
> 
>     * Remove `awestruct-ibeams`
> 
>     * Scan Organization Triggers  set to 1day (instead of 1 week)
> 
>     * Orphaned Item Strategy
>       -> Enable Abort builds
>       -> Discard old items (no max day, no max items)

```
[Wed Jul 05 16:26:44 UTC 2023] Finished organization scan. Scan took 19 sec
Evaluating orphaned items in Infra
Will remove awestruct-ibeams
Finished: SUCCESS
```

**Comment by dduportal** [comment] 2023-07-05 16:29
For the https://ci.jenkins.io/job/jenkinsfile-runner organization scanning, applying the following change (will trigger an indexation):

* Exclude archived repositories
* Orphaned Item Strategy
  -> Enable Abort builds
  -> Discard old items (no max day, no max items)

**Comment by dduportal** [comment] 2023-07-05 16:34
> For the https://ci.jenkins.io/job/jenkinsfile-runner organization scanning, applying the following change (will trigger an indexation):
> 
>     * Exclude archived repositories
> 
>     * Orphaned Item Strategy
>       -> Enable Abort builds
>       -> Discard old items (no max day, no max items)

```
[Wed Jul 05 16:32:12 UTC 2023] Finished organization scan. Scan took 53 sec
Finished: SUCCESS
```

**Comment by dduportal** [comment] 2023-07-05 16:58
For the https://ci.jenkins.io/job/jenkinsci-libraries organization scanning, applying the following change (will trigger an indexation):

* Exclude archived repositories
* Orphaned Item Strategy
  -> Enable Abort builds
  -> Discard old items (no max day, no max items)

**Comment by dduportal** [comment] 2023-07-05 17:02
> For the https://ci.jenkins.io/job/jenkinsci-libraries organization scanning, applying the following change (will trigger an indexation):
> 
>     * Exclude archived repositories
> 
>     * Orphaned Item Strategy
>       -> Enable Abort builds
>       -> Discard old items (no max day, no max items)

```
[Wed Jul 05 17:00:17 UTC 2023] Finished organization scan. Scan took 2 min 25 sec
Evaluating orphaned items in Libraries
Will remove bytecode-compatibility-transformer
Will remove extras-executable-war
Finished: SUCCESS
```

**Comment by dduportal** [comment] 2023-07-05 17:03
For the https://ci.jenkins.io/job/Packaging/ organization scanning, applying the following change (will trigger an indexation):

* Exclude archived repositories
* Orphaned Item Strategy
    -> Enable Abort builds
    -> Discard old items (no max day, no max items)

**Comment by dduportal** [comment] 2023-07-05 17:07
> For the https://ci.jenkins.io/job/Packaging/ organization scanning, applying the following change (will trigger an indexation):
> 
>     * Exclude archived repositories
> 
>     * Orphaned Item Strategy
>       -> Enable Abort builds
>       -> Discard old items (no max day, no max items)

```
[Wed Jul 05 17:05:04 UTC 2023] Finished organization scan. Scan took 1 min 53 sec
Evaluating orphaned items in Packaging
Will remove jnlp-agents
Will remove docker-ssh-slave
Will remove docker-jnlp-slave
Will remove docker-slave
Finished: SUCCESS
```

**Comment by dduportal** [comment] 2023-07-05 17:08
For the https://ci.jenkins.io/job/Stapler/ organization scanning, applying the following change (will trigger an indexation):

* Exclude archived repositories
* Orphaned Item Strategy
  -> Enable Abort builds

**Comment by dduportal** [comment] 2023-07-05 17:12
> For the https://ci.jenkins.io/job/Stapler/ organization scanning, applying the following change (will trigger an indexation):
> 
>     * Exclude archived repositories
> 
>     * Orphaned Item Strategy
>       -> Enable Abort builds

```
[Wed Jul 05 17:09:12 UTC 2023] Finished organization scan. Scan took 11 sec
Finished: SUCCESS
```

**Comment by dduportal** [comment] 2023-07-05 17:13
Setup applied everywhere. I'm closing, thanks @NotMyFault !

Feel free to reopen if I missed anything!

**Closed by dduportal** 2023-07-05 17:13 UTC
Labels: ci.jenkins.io
