### ISSUE TITLE
`maven-17` label hanging on ci.jenkins.io

### ISSUE THREAD

**Issue by jglick** [jenkins-infra/helpdesk#3391] opened 2023-02-15 23:00 UTC
### Service(s)

ci.jenkins.io

### Summary

For example https://ci.jenkins.io/job/Plugins/job/workflow-durable-task-step-plugin/job/PR-291/1/execution/node/12/log/ has, as of this writing, been waiting for more than an hour

> All nodes of label ‘[maven-17](https://ci.jenkins.io/label/maven-17/)’ are offline

**Comment by jglick** [comment] 2023-02-15 23:02
(BTW I would recommend adding a link to https://github.com/jenkins-infra/helpdesk/issues/new/choose to the ci.jenkins.io description, to make it obvious where to file issues.)

**Comment by dduportal** [comment] 2023-02-16 07:36
European morning shift: 

- No more build queue : I'm triggering a new BOM build (master branch) trying to reproduce the issue
- Reporting messages in the IRC channel by @MarkEWaite:

> The [ci.jenkins.io](http://ci.jenkins.io/) build queue seemed to be growing without allocating new container agents. I canceled 4 bom pull requests to reduce the queue form 650 to 12. Still does not seem able to allocate maven-17 agents, though only a few have been requested.
> Likewise was not able to allocate maven-11 agents. I was able to allow a few jobs to complete successfully by temporarily assigning the maven-11 label to the s390x agent.

    - Checking the s390x agent: it has no `maven-11` left, so it was proprley cleaned up (thanks!)

**Comment by lemeurherve** [comment] 2023-02-16 07:56
> (BTW I would recommend adding a link to [jenkins-infra/helpdesk/issues/new/choose](https://github.com/jenkins-infra/helpdesk/issues/new/choose) to the ci.jenkins.io description, to make it obvious where to file issues.)

Great suggestion, I've added a fourth link:
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/91831478/219302549-18b885af-c90b-45b7-8463-5735152d433f.png">

**Comment by dduportal** [comment] 2023-02-16 07:59
- Additional update of the description (we crossed path with @lemeurherve 😅)

<img width="1305" alt="Capture d’écran 2023-02-16 à 08 58 28" src="https://user-images.githubusercontent.com/1522731/219303325-b734e6fa-591e-4f1c-b82e-f278f96a666d.png">

- The bom builds is running well. it's weird. Gotta try with even more builds.

**Comment by jglick** [comment] 2023-02-16 21:02
Still seems constipated.

**Comment by dduportal** [comment] 2023-02-17 12:06
Hello, sorry for the inconvenience @jglick .

Yesterday (morning in the EU, night in the US) and to day (same timeline), we checked ci.jenkins.io but did not saw blocked queue.

However @smerle33 and @lemeurherve saw the build queue being filled and then treated in more or less 1h30 .

As for now, by checking the Load statistics of ci.jenkins.io, we clearly see the build peaks from yesterday and today:

<img width="1694" alt="Capture d’écran 2023-02-17 à 12 44 49" src="https://user-images.githubusercontent.com/1522731/219648667-00ba683f-8b61-4267-8ee3-e1ab53fdb776.png">

<img width="1696" alt="Capture d’écran 2023-02-17 à 08 48 02" src="https://user-images.githubusercontent.com/1522731/219648699-edd89902-c604-4d62-9a7e-aaa454b405ef.png">

These statistics clearly shows 2 things:

- The build demand generate more frequent peaks (not of the pattern, but it is clearly more frequent)
- The agent allocation is quite good and behaves as expected (given the current setup) and always reaches the same "plateau" of 150 linux containers (a bit more including Windows containers, and VM agents).

=> It gives us a confirmation (and a way to measure if effective, at least from allocation perspective) that:

- We need more capacity => we're going to increase Digital Ocean capacity for linux containers, and we'll try to quickly increase sponsorships (we have some targets: CivoCloud, OVH, Scaleway, etc.). Besides, we have a margin  (1.5k€ monthly) in Azure that could help in medium term
- We might need to split the bom workload from the other workloads (to void blocking core or plugin developers when a peak of bom builds happens)

Other ideas?

**Comment by jglick** [comment] 2023-02-17 12:08
Yeah is there some way to deprioritize `bom` agents?

**Comment by dduportal** [comment] 2023-02-17 12:11
> Yeah is there some way to deprioritize bom agents?

Idea discussed with other people last month (not detailling the "how", only the "what"):

- 1 pool of agents for "non BOM" builds
- 1 pool of agents for "BOM" 's principal branch builds, only 1 build at a time
- 1 pool of agents for "BOM" PRs builds (as many build as we want)

WDYT ?

**Comment by jglick** [comment] 2023-02-17 12:59
I did not mean to divide anything into “pools”, only to ensure that if there are BOM and non-BOM queue items waiting for an available executor, take a non-BOM item first since it is more likely some developer is actually waiting for it.

Even better, if we could figure out how to do it: deprioritize all non-PR builds, as well as all builds of PRs filed by Dependabot. Sometimes developers _are_ waiting for BOM builds, and usually developers are not waiting for trunk or DB builds in plugins. (Well, trunk builds sometimes, if you are expecting a JEP-229 deployment.)

https://plugins.jenkins.io/PrioritySorter/ sounds vaguely right though it is unclear whether its Pipeline support is complete (no Pipeline test coverage AFAICT), and I see no evidence it has any multibranch logic whatsoever. https://plugins.jenkins.io/fast-track/ also sounds vaguely right but appears unmaintained and also probably lacks Pipeline support, much less multibranch. https://www.jenkins.io/doc/developer/extensions/jenkins-core/#queuesorter does not indicate anything else relevant. I suppose I could write a one-off plugin with a simple `QueueSorter` implementation that drops multibranch non-PR & DB builds to the bottom of the queue without configuration, though I can see the lords of hosting demanding that this be folded into one of the existing plugins (which would be much more effort).

**Comment by dduportal** [comment] 2023-02-17 13:34
Thanks for the detailled explanation @jglick . It make sense, but I have no idea how, as a Jenkins administrator, to dynamically customize the priorites of a Jenkins build queue. I assume, based on your message, that some work is needed on a plugin that would help Jenkins to drive its build queue. I'm not aware of any other "method": if there are some (even tricky) we would be interested.

The "pool" idea is far from perfect, but at least splitting the workload ability between BOM and non-BOM is easy and would help a bit (without solving the "priority" issue of course) to avoid frustrating plugin developers.

**Comment by jglick** [comment] 2023-02-17 13:45
I wonder if it would make sense to have a plugin dedicated to customizations we want in ci.jenkins.io that we can iterate on rapidly (and which would either be suppressed from the public UC or clearly marked as inapplicable to anyone else); interesting features that seem more broadly useful and have been proven by experience to work could be generalized and then “sedimented” to usual plugins.

**Comment by dduportal** [comment] 2023-02-22 17:29
- Increasing the Digital Ocean maximum to 50 nodes failed due to a cloud limit (avoiding malicious usage)
  - PR https://github.com/jenkins-infra/digitalocean/pull/103 (terraform plan does not check the cloud limit on the digital ocean provider)
  - Error message: `Error: Error updating node pool: Unable to update nodepool: PUT https://api.digitalocean.com/v2/kubernetes/clusters/<redacted>/node_pools/<redacted>: 422 (request "<redacted>") validation error: autoscale desired max nodes exceed limits, 45 additional nodes but not enough available droplet limit`
  - We contacted Digital Ocean to increase the upper limit to 60 droplets (50 + 2 + 4 +1 + margin)

**Comment by dduportal** [comment] 2023-02-22 17:38
- Increased to 22 max nodes on digitalocean (maximum available for now as per the DigitalOcean UI)
- Increased the ci.jenkins.io capacity from 150 to 216 concurent builds: https://github.com/jenkins-infra/jenkins-infra/pull/2655

**Comment by dduportal** [comment] 2023-02-22 17:52
Before closing this issue, we have to define a new "split" node pool that should not be usable by the BOM builds.

**Comment by lemeurherve** [comment] 2023-03-07 11:19
For the record, I've added a paragraph to ci.jenkins.io description pointing to https://ci.jenkins.io/load-statistics

<img width="899" alt="image" src="https://user-images.githubusercontent.com/91831478/223407652-dc5949a4-fd12-4806-9697-3f3fc25342e4.png">

**Comment by lemeurherve** [comment] 2023-03-07 13:51
> - Increased to 22 max nodes on digitalocean (maximum available for now as per the DigitalOcean UI)
> - Increased the ci.jenkins.io capacity from 150 to 216 concurent builds: https://github.com/jenkins-infra/jenkins-infra/pull/2655

The total ci.jenkins.io capacity has been increased from 216 to 300 with the following PRs:
- https://github.com/jenkins-infra/digitalocean/pull/106
- https://github.com/jenkins-infra/kubernetes-management/pull/3661
- https://github.com/jenkins-infra/jenkins-infra/pull/2679

**Comment by dduportal** [comment] 2023-03-07 14:11
Confirmed that the increased capacity is available on ci.jenkins.io. We currently have a high load of BOM builds and both clusters are using `150` agents.

**Closed** 2023-03-20 17:26 UTC
Labels: bug, ci.jenkins.io
