### ISSUE TITLE
Wrong update-center returned for 2.452.4

### ISSUE THREAD

**Issue by kinjalik** [jenkins-infra/helpdesk#4427] opened 2024-11-28 08:50 UTC
### Service(s)

Update center

### Summary

When trying to manually fetch update-center.json for version 2.452.4 (LTS) I got the file for 2.487

### Reproduction steps

1. Open `https://updates.jenkins.io/update-center.json?version=2.452.4`
2. Check out the field `core.version`, it will contain the number of weekly 2.487

**Comment by dduportal** [comment] 2024-11-28 08:57
Duplicate of #4428: there is(was) an incident in progress.

Not closing though: can you confirm it is now working @kinjalik please?

**Comment by szjozsef** [comment] 2024-11-28 09:05
@dduportal It seems to be solved

**Comment by kinjalik** [comment] 2024-11-28 09:14
Yes, can confirm it redirects to UC of 2.479.2. Not sure it's still correct though, but I'll try to install plugins from that one a bit later

**Comment by dduportal** [comment] 2024-11-28 09:42
I don't remember the details of this "version mismatch" but I can confirm that the issue is not due to the new Update Center system: the old update center serves the same content with the core version set to 2.479.2 so I guess we're in a case where 2.452.4 and 2.479.2 might not have difference regarding incompatible plugins

**Comment by dduportal** [comment] 2024-11-28 09:46
> I don't remember the details of this "version mismatch" but I can confirm that the issue is not due to the new Update Center system: the old update center serves the same content with the core version set to 2.479.2 so I guess we're in a case where 2.452.4 and 2.479.2 might not have difference regarding incompatible plugins

Ping @daniel-beck @timja could you help me refreshing my memory on the "why" here?

**Comment by daniel-beck** [comment] 2024-11-28 09:54
The JSON offers the latest release of the same line as requested. That's 2.479.2 when providing a current version of 2.452.2. Why would the JSON reflect back the same version you already have?

**Comment by daniel-beck** [comment] 2024-11-28 09:57
Also, this is not supported API. Whatever you're doing may break at any time if we feel like it. Use Jenkins's plugin manager and/or `jenkins-plugin-cli` in the Docker containers.

**Comment by dduportal** [comment] 2024-11-28 10:07
> Also, this is not supported API. Whatever you're doing may break at any time if we feel like it. Use Jenkins's plugin manager and/or `jenkins-plugin-cli` in the Docker containers.

The initial issue (during the outage earlier today) was about the URL `https://updates.jenkins.io/update-center.json?version=2.452.4` => this one is supprted right?

(The "dynamic-XXX" URL is only the reported Location for the HTTP/302 triggered by Apache2 itself IIUC)

**Comment by dduportal** [comment] 2024-11-28 10:08
THanks @daniel-beck for the explanation! It's way better than my gut feeling and my words :D

**Comment by daniel-beck** [comment] 2024-11-28 11:11
> this one is supported right?

"Supported" as in this is what Jenkins contacts. We do not support processing contents of the file outside Jenkins or tools we provide.

As an example, there is some content in these files that's unused by Jenkins and that we may remove at any time. Even content used by Jenkins may be removed if we're willing to degrade the experience for some other goal. If someone's `jq` expression relies on that kind of content, tough.

As an extreme example, if we were to start denying all `User-Agent`s that aren't Java to accomplish some load/cost/stability goal, and it works for our infra, I would see no problem with that.

**Comment by kinjalik** [comment] 2024-11-28 15:06
In fact, `curl` command was used to provide a representative reproduction steps to clearly indicate the issue inside the given `update-center.json`  :)

Anyways thank you guys for your answers and support

I'm not sure if I'm supposed to close an issue by myself or there is some process you follow, sorry about that

**Comment by dduportal** [comment] 2024-11-29 13:55
> I'm not sure if I'm supposed to close an issue by myself or there is some process you follow, sorry about that

No worries, we are taking care of triage! Many many thanks for reporting and confirming, it helped!

**Comment by dduportal** [comment] 2024-11-29 13:56
Note:

- Incident closed by https://github.com/jenkins-infra/status/pull/563
- Long term fix applied in https://github.com/jenkins-infra/helpdesk/issues/4402

**Closed by dduportal** 2024-11-29 13:55 UTC
Labels: updateCenter
