### ISSUE TITLE
ci.jenkins.io reports HTTP 502 for many jobs

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#4158] opened 2024-06-29 19:36 UTC
### Service(s)

ci.jenkins.io

### Summary

When I try to open https://ci.jenkins.io/job/Plugins/job/elastic-axis-plugin/ and many other jobs, the response is an error page with proxy error

### Reproduction steps

Attempt to open any one of these jobs:

* https://ci.jenkins.io/job/Plugins/job/elastic-axis-plugin/
* https://ci.jenkins.io/job/Plugins/job/apache-httpcomponents-client-4-api-plugin/
* https://ci.jenkins.io/job/Plugins/job/authorize-project-plugin/
* https://ci.jenkins.io/job/Plugins/job/basic-branch-build-strategies-plugin/
* https://ci.jenkins.io/job/Plugins/job/embeddable-build-status-plugin/
* https://ci.jenkins.io/job/Plugins/job/git-client-plugin/
* https://ci.jenkins.io/job/Plugins/job/git-plugin/
* https://ci.jenkins.io/job/Plugins/job/implied-labels-plugin/
* https://ci.jenkins.io/job/Plugins/job/markdown-formatter-plugin/
* https://ci.jenkins.io/job/Plugins/job/nodelabelparameter-plugin/
* https://ci.jenkins.io/job/Plugins/job/platformlabeler-plugin/
* https://ci.jenkins.io/job/Plugins/job/pollscm-plugin/
* https://ci.jenkins.io/job/Plugins/job/priority-sorter-plugin/
* https://ci.jenkins.io/job/Plugins/job/schedule-build-plugin/
* https://ci.jenkins.io/job/Plugins/job/testng-plugin-plugin/
* https://ci.jenkins.io/job/Plugins/job/versioncolumn-plugin/
* https://ci.jenkins.io/job/Plugins/job/xshell-plugin/

**Comment by dduportal** [comment] 2024-07-01 09:32
Starting analysis with @smerle33 , we'll report here

**Comment by dduportal** [comment] 2024-07-01 09:45
Updated status.jenkins.io with https://github.com/jenkins-infra/status/pull/516

**Comment by dduportal** [comment] 2024-07-01 12:53
Update: 

- We (at least temporarily) fixed the problem after a few operations involving controller restarts
- The issue started after the upgrade of Docker CE to 27.0.2 on this machine. It could be tied to the associated plugin update though.
- The system logs of the VM showed a LOT of IPv6 network errors with the `docker0` interface.
- We [upgraded Docker to 27.0.3](https://github.com/jenkins-infra/jenkins-infra/pull/3507) and it solved the issue (restarted the controller). Sounds like https://github.com/moby/moby/issues/48067. 
- We upgraded all controller plugins (except datadog) to ensure a second (and controlled) restart was applied: the issue did not re-appear.

**Comment by dduportal** [comment] 2024-07-01 12:55
The issue is not back after 2 hour. I'm closing as it looks fixed: feel free to reopen if it comes back.

**Closed by dduportal** 2024-07-01 12:55 UTC
Labels: ci.jenkins.io
