### ISSUE TITLE
Builds are often failing with timeout due to Artifactory being slow

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#2733] opened 2022-01-13 11:08 UTC
### Service

ci.jenkins.io

### Summary

A plugin with no Java code which should build in ~1min or less is still building after 30 mins

https://github.com/jenkinsci/jenkins-infra-test-plugin/pull/16
https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fjenkins-infra-test-plugin/detail/PR-16/3/pipeline/

**Comment by jglick** [comment] 2022-01-13 14:44
Smells like an Artifactory issue. https://issues.apache.org/jira/browse/MNG-6976 as usual.

**Comment by dduportal** [comment] 2022-01-13 15:01
- Confirmled that the download speed is the culprit: https://ci.jenkins.io/job/Plugins/job/jenkins-infra-test-plugin/job/PR-16/8/console
- I can reproduce on my local ISP (Belgium)
- We opened an issue at JFrog support: https://groups.google.com/g/jenkins-infra/c/laSsgPOH9qs

Thanks @jglick @timja for reporting!

**Comment by jmMeessen** [comment] 2022-01-13 15:21
My case of build slowness: a full CI of `config-file-provider` (https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fconfig-file-provider-plugin/activity) takes about 30 minutes.

It now fails (after timeout exhaustion)  after 1 hour. See for example https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fconfig-file-provider-plugin/detail/master/169/pipeline

**Comment by lemeurherve** [comment] 2022-01-17 14:09
There seems to be some issues again, reopening.

**Comment by jmMeessen** [comment] 2022-01-18 10:54
It looks like we are experiencing a similar disruption: build take much more than usual to build. While it usually takes max 30 mins, it is still building at 53 minutes. https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fconfig-file-provider-plugin/detail/master/172/pipeline/

**Comment by jmMeessen** [comment] 2022-01-20 10:24
@dduportal @lemeurherve FYI:
I started a build on `config-file-provider` plugin beginning of the EU morning and it worked : no timeout/kill after 1 hour. The build took the usual 30 minutes.
I merged another PR right now. Let's see if the good news is confirmed.

**Comment by dduportal** [comment] 2022-01-20 11:05
We just got a feedback from JFrog in https://groups.google.com/g/jenkins-infra/c/j7M49evRXJg/m/9FG7uoQkAQAJ .

Are your builds speed improving?

**Comment by jmMeessen** [comment] 2022-01-20 11:21
I am sad to say that the last build was shot down after 1 hour: https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fconfig-file-provider-plugin/detail/master/177/pipeline

**Comment by jmMeessen** [comment] 2022-01-20 11:22
Change was concurrent. will try again

**Comment by timja** [comment] 2022-01-20 14:42
This also failed with the same issue: https://github.com/jenkinsci/azure-container-agents-plugin/pull/97
(1 hour ago)

and Reinhold yes same issue, that is a nice feature of gradle 😄

**Comment by timja** [comment] 2022-01-20 14:56
JFrog just upgraded our instance and it works for me on my machine now fine.

**Comment by timja** [comment] 2022-01-20 15:18
Seems fixed to me now, the build above that was failing now works

**Comment by reinholdfuereder** [comment] 2022-01-21 09:30
Unfortunately it is happening again:
Please note that this is a clean build (without any Gradlew cache whatsoever due to a clean Docker container and no Docker volume), so all dependencies must be fetched again and again.
And I triggered this build a few times this morning (i.e in the previous 3.5h; now it is ~10:30 Europe/Vienna timezone):
* still OK at ~08:00
* slow since at least ~09:45 (but not extremely slow, just significantly slower)
  * E.g. 
![grafik](https://user-images.githubusercontent.com/145182/150502222-04f2037f-b971-46f6-b257-0429f1c67bd4.png)

**Comment by lemeurherve** [comment] 2022-01-21 09:36
Back to an average of 5Kb/s download rate too.

**Comment by dduportal** [comment] 2022-01-21 09:55
Pinged Jfrog: https://groups.google.com/g/jenkins-infra/c/j7M49evRXJg/m/JREWgDJvAQAJ

**Comment by MarkEWaite** [comment] 2022-01-22 14:13
Reported as resolved in the email thread at https://groups.google.com/g/jenkins-infra/c/j7M49evRXJg/m/3UhhLNl9AQAJ

**Closed by MarkEWaite** 2022-01-22 14:13 UTC
Labels: artifactory, ci.jenkins.io, site:ci.jenkins.io
