### ISSUE TITLE
Test history page on ci.jenkins.io for core builds is inaccessible

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3648] opened 2023-07-05 09:27 UTC
### Service(s)

ci.jenkins.io

### Summary

Navigating to the test result page for core builds yields:

![Screenshot 2023-07-05 at 11 26 54](https://github.com/jenkins-infra/helpdesk/assets/13383509/7f82e8f0-8ae0-4af9-a588-7e055e42c78e)

### Reproduction steps

1. Navigate to https://ci.jenkins.io/job/Core/job/jenkins/job/master/5143/testReport/hudson.diagnosis/HudsonHomeDiskUsageMonitorTest/
2. Click on "Took xx min xx sec":
![Screenshot 2023-07-05 at 11 26 30](https://github.com/jenkins-infra/helpdesk/assets/13383509/753aae94-d3a6-4a46-91ac-04bf528d312e)
3. Get the error I attached above

**Comment by dduportal** [comment] 2023-07-05 11:09
Caused by the operation in https://github.com/jenkins-infra/helpdesk/issues/3535

**Comment by dduportal** [comment] 2023-07-05 12:23
Analysis in progress, but I'm blocked by https://github.com/jenkins-infra/azure/pull/424

**Comment by dduportal** [comment] 2023-07-05 13:30
The error is thrown by Apache:

```
[Wed Jul 05 13:25:43.780721 2023] [proxy_http:error] [pid 673:tid 140072253978176] (70007)The timeout specified has expired: [client xxxxxxx:55530] AH01102: error reading status line from remote server localhost:8080, referer: https://ci.jenkins.io/job/Core/job/jenkins/job/master/5143/testReport/hudson.diagnosis/HudsonHomeDiskUsageMonitorTest/

[Wed Jul 05 13:25:43.780749 2023] [proxy:error] [pid 673:tid 140072253978176] [client xxxxxxx:55530] AH00898: Error reading from remote server returned by /job/Core/job/jenkins/job/master/5143/testReport/hudson.diagnosis/HudsonHomeDiskUsageMonitorTest/history/, referer: https://ci.jenkins.io/job/Core/job/jenkins/job/master/5143/testReport/hudson.diagnosis/HudsonHomeDiskUsageMonitorTest/
```


No error logs (at first sight) in Jenkins while loading the request. Trying through an SSH tunnel to remove Apache from the mix and see the result in direct access

**Comment by uhafner** [comment] 2023-07-06 09:57
Might be related to https://github.com/jenkinsci/junit-plugin/pull/546?

**Comment by dduportal** [comment] 2023-07-06 13:41
> Might be related to [jenkinsci/junit-plugin#546](https://github.com/jenkinsci/junit-plugin/pull/546)?

It could be, but we haven't updated to the Junit plugin version with the fix (I'm not sure if the problem would be caused OR fixed by the  aforementionned change 😅 )


But after https://github.com/jenkins-infra/helpdesk/issues/3643#issuecomment-1623329704, we ran the build discarder which did not fail (as the artefact deletion is not blocking) on the `master` branch of the Jenkins Core, which removed ~2Gb of data in the job directory.

And... now, the page answers (it is not immediate but no more proxy error).

I understand that the information in the page are constructed from the list of builds for a given pipeline which explains why it would have been so slow.

I'm closing this issue @NotMyFault @uhafner thanks for reporting and helping. Feel free to reopen if you still have the error!

**Closed by dduportal** 2023-07-06 13:41 UTC
Labels: bug, ci.jenkins.io

**Comment by uhafner** [comment] 2023-07-06 18:53
The mentioned PR is the fix, sorry for the confusion...

**Comment by dduportal** [comment] 2023-07-07 16:27
> The mentioned PR is the fix, sorry for the confusion...

No problem, it was extremely nice that you helped so no problem

**Comment by dduportal** [comment] 2023-07-07 16:35
For info, upgraded to the latest `junit` but it did not change anything: loading time is between 30 to 40s
