### ISSUE TITLE
Create a new credential for Packer as code with terraform

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#3439] opened 2023-03-09 09:31 UTC
### Service(s)

infra.ci.jenkins.io, Other

### Summary

Import and manage the Azure Packer Application Credential as code to deal automatically with the renewal.

as per https://github.com/jenkins-infra/helpdesk/issues/3416

First create the skeleton from the trusted.ci template, then import the ressources within terraform states.

**Comment by dduportal** [comment] 2023-03-09 18:13
- https://github.com/jenkins-infra/azure/pull/288 merged 👍 
- Permission error with the SP: might be related to its former owner not being `terraform-production`

=> Let's pair on the following steps now:
- Manually remove the SP
- Ensure that the Terraform job creates the SP and the Azure AD password
- Get the new SP ID (+ AD password secret value) and add them to infra.ci.jenkins.io creential for the packer job and test them
- Add an event in the calendar for the password rotation (thanks @lemeurherve ;) )

**Comment by smerle33** [comment] 2023-03-10 14:34
- OLD SP been removed : 'az ad sp delete --id 53078417-ff2a-44c4-9f9e-8cd2f822737e`
- terraform job launched : 
   ```
   [2023-03-10T14:24:56.677Z] Plan: 2 to add, 0 to change, 0 to destroy.
   [2023-03-10T14:24:57.283Z] azuread_service_principal.packer: Creating...
   [2023-03-10T14:24:57.283Z] azuread_application_password.packer: Creating...
   [2023-03-10T14:24:58.370Z] azuread_service_principal.packer: Creation complete after 1s [id=....]
   [2023-03-10T14:25:02.818Z] azuread_application_password.packer: Creation complete after 5s [id=.../password/...]
   [2023-03-10T14:25:02.818Z] 
   [2023-03-10T14:25:02.818Z] Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
   ```

**Comment by smerle33** [comment] 2023-03-10 14:52
SP and secrets updated in soaps, waiting for kubernet-management to process the main build (when ready)

**Comment by dduportal** [comment] 2023-03-10 17:57
As debugged together:

- You correctly applied the new credentials, but an HTTP/400 error is sent when using it to log-in to the Azure API
- The error says (both locally and in Jenkins) that "no subscription associated with the appID".
- It looks like that we need to add a role assignement to the SP:
  - WiP: https://github.com/jenkins-infra/azure/pull/291
  - both trusted_ci_jenkins_io SP and the old `packer` SP have/had this assignement. But it was not imported in terraform.

**Comment by dduportal** [comment] 2023-03-12 22:07
Applied the new credential successfully 👍

**Comment by dduportal** [comment] 2023-03-20 15:05
Status:

- Packer builds are failing early on Azure with the following error:

```console
resources.GroupsClient#CheckExistence: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF
```

- This error indicates that the SP used by Packer does not have the permission to manage resource groups in the subscription.

- Confirmed by Packer's documentation (https://developer.hashicorp.com/packer/plugins/builders/azure/arm#service-principal):

> The service principal specified in client_id must have full access to this subscription, unless build_resource_group_name option is specified in which case it needs to have owner access to the existing resource group specified in build_resource_group_name parameter.

**Comment by dduportal** [comment] 2023-03-20 17:16
All is good 🥳

**Closed by dduportal** 2023-03-20 17:16 UTC
Labels: infra.ci.jenkins.io
