### ISSUE TITLE
`jenkins/jenkins:lts` images are missing `arm64` & `s390x`

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#2890] opened 2022-04-19 02:53 UTC
### Service(s)

Docker Hub

### Summary

The containers for `jenkins/jenkins:lts` and `jenkins/jenkins:lts-jdk11` were rebuilt recently and the rebuilt images do not include `arm64` or `s390x` images.

The containers for `jenkins/jenkins:2.332.2-lts` and `jenkins/jenkins:2.332.2-lts-jdk11` include the `arm64` and `s390x` images.

See https://community.jenkins.io/t/docker-hub-jenkins-jenkins-lts-image-amd64-only/2143 for the initial report.

### Reproduction steps

1. Open https://hub.docker.com/r/jenkins/jenkins/tags?page=1&name=lts-jdk11
2. Compare the available platforms for `lts-jdk11` and `2.332.2-lts-jdk11`, note that `s390x` and `arm64` are available for one and not the other

**Comment by dduportal** [comment] 2022-04-19 14:11
Alas we only have build logs up to the 7th of paril, while the LTS 2.332.2 was released the 6th: we cannot diagnose the root cause (e.g. "why did the deployment or armd64 and s390x failed for this LTS").

However, we can still act: the publication script at https://github.com/jenkinsci/docker/blob/dfccdeee9e54c2edee6d011b062baf979bcdf4eb/.ci/publish.sh#L35-L51 only check for a tag, in the DockerHub API, to decide if it is published or not.

We have to update this script to check for each CPU architecture declared for a given tag, to let it decide if it has to be rebuilt/deployed or not. By doing so, we can trigger the daily container build, that should detect the missing architectures and that will build + deploy it.

@timja WDYT?

**Comment by timja** [comment] 2022-04-19 14:15
Please go ahead, whatever patch is required, we've hacked the script before for similar issues like this

**Comment by dduportal** [comment] 2022-04-19 17:25
Interesting:

```
skopeo inspect docker://jenkins/jenkins:2.332.1-lts-jdk11      
FATA[0001] Error parsing manifest for image: choosing image instance: no image found in manifest list for architecture amd64, variant "", OS darwin
```

**Comment by MarkEWaite** [comment] 2022-04-19 18:02
Surprising result from recent builds.

* `latest` was pushed an hour ago and has no `arm64` and no `s390x`
* `latest-jdk11` was pushed 4 hours ago and has `arm64` and `s390x`
* `2.344-jdk11` was pushed 4 hours ago and has `arm64` and `s390x`

Maybe an unexpected job ran and pushed to `latest`?

**Comment by basil** [comment] 2022-04-20 15:46
I noticed this a week or two ago when I tried to upgrade on my AWS `t4g.small` installation (Ubuntu 20.04.4 LTS aarch64). I can verify the fix if needed.

**Comment by dduportal** [comment] 2022-04-20 16:46
> Maybe an unexpected job ran and pushed to latest?

That's what it looks like. it's worrying. Currently searching which job could do this.

**Comment by dduportal** [comment] 2022-04-20 17:14
Found the culprit: https://trusted.ci.jenkins.io:1443/job/Containers/job/Core%20Release%20Containers/job/quickstart/ .
The `quickstart` branch (https://github.com/jenkinsci/docker/tree/quickstart) is picked and built.

I'm filtering this branch out of the multibranch to avoid messing up future builds.

**Comment by dduportal** [comment] 2022-04-20 17:14
> Found the culprit: https://trusted.ci.jenkins.io:1443/job/Containers/job/Core%20Release%20Containers/job/quickstart/ . The `quickstart` branch (https://github.com/jenkinsci/docker/tree/quickstart) is picked and built.
> 
> I'm filtering this branch out of the multibranch to avoid messing up future builds.

That is the root cause of the ARM64 / s390x disappearing.

**Comment by dduportal** [comment] 2022-04-22 12:50
@timja @MarkEWaite Opened https://github.com/jenkinsci/docker/pull/1326 to fix the publication. That should rebuild and republish all the versions of the current LTS baseline + previous LTS + all weekly since then (see my comment).

I'll monitor the publication build on trusted.ci once merged.

**Comment by dduportal** [comment] 2022-04-22 15:16
Let's wait for Monday 25

**Comment by dduportal** [comment] 2022-04-26 14:19
@timja @MarkEWaite I've just opened a 2nd PR https://github.com/jenkinsci/docker/pull/1332 that should fix this. Local tests looks good to me.

**Comment by MarkEWaite** [comment] 2022-04-26 20:44
The run of jenkinsci/docker#1332 on trusted.ci published several updated images (for example, `jenkins/jenkins:2.332.2` previously contained `git lfs 3.0.2` and the newly published image includes `git lfs 3.1.4` as hoped) but then seemed to stop its progress.  I've scheduled another run to start in 6 hours just in case there is something related to Docker rate limits.

**Comment by dduportal** [comment] 2022-04-27 07:51
I confirm that the last 3 builds ran successfully last night (EU timezone) and that the non intel images are now available:

```console
skopeo inspect --raw docker://docker.io/jenkins/jenkins:lts      
{
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "schemaVersion": 2,
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "digest": "sha256:503ca622af90d5def3a2af92b4aa94a56020227a47a486b5d23caf5e6fdece1c",
         "size": 3876,
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "digest": "sha256:ad89a05f27003217f9e3df21770d1b18f55263760011471c61e67f6d1d9f23b3",
         "size": 3876,
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "digest": "sha256:fadd01b5d9fd6a3ce1a79c1940b36855fce8899eba1d5a4969972b69f5ea3808",
         "size": 3876,
         "platform": {
            "architecture": "s390x",
            "os": "linux"
         }
      }
   ]
}  
```

```console
skopeo inspect --raw docker://docker.io/jenkins/jenkins:lts-jdk11
{
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "schemaVersion": 2,
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "digest": "sha256:503ca622af90d5def3a2af92b4aa94a56020227a47a486b5d23caf5e6fdece1c",
         "size": 3876,
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "digest": "sha256:ad89a05f27003217f9e3df21770d1b18f55263760011471c61e67f6d1d9f23b3",
         "size": 3876,
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "digest": "sha256:fadd01b5d9fd6a3ce1a79c1940b36855fce8899eba1d5a4969972b69f5ea3808",
         "size": 3876,
         "platform": {
            "architecture": "s390x",
            "os": "linux"
         }
      }
   ]
}
```

**Closed** 2022-04-27 07:51 UTC
Labels: dockerhub

**Comment by MarkEWaite** [comment] 2022-04-27 13:57
Thanks very much @dduportal !  I confirm as well that the 2.345 Docker images are available and have the expected platform images.
