### ISSUE TITLE
Latest alpine-lts image is broken

### ISSUE THREAD

**Issue by Re4zOon** [jenkins-infra/helpdesk#3721] opened 2023-08-19 07:04 UTC
### Service(s)

Docker Hub

### Summary

The latest alpine-lts image wont start, as its based on java8:
```
Running with Java 8 from /usr/lib/jvm/java-1.8-openjdk/jre, which is older than the minimum required version (Java 11).
Supported Java versions are: [11, 17]
See https://jenkins.io/redirect/java-support/ for more information.
```

https://hub.docker.com/layers/jenkins/jenkins/lts-alpine/images/sha256-69ab567f0323544d0eaed78f1991dfb64a5fed95a4100264d68e5f99073ba9ee?context=explore

Not sure how it happened, please fix the pipelines for it.

Also an interesting story, as I tried to fall back to the previous image I tried to grab the digest from docker:
```
[root@jenkins ~]# docker image ls --digests
REPOSITORY                                                       TAG                  DIGEST                                                                    IMAGE ID       CREATED        SIZE
jenkins/jenkins                                                  lts-alpine           sha256:69ab567f0323544d0eaed78f1991dfb64a5fed95a4100264d68e5f99073ba9ee   447f5f160722   18 hours ago   247MB
jenkins/jenkins                                                  2.401.3-lts-alpine   sha256:21531ce1823b0410260f3ad0fce8fd5fdbc10056595cd46f89a5671cea0af480   73b4013cbb8f   3 weeks ago    258MB
```

As you can see the previous digest is 21531ce[...], but according to docker hub its d404158e[...]:
https://hub.docker.com/layers/jenkins/jenkins/2.401.3-lts-alpine/images/sha256-d404158eae77dfbbbd642adfcccaa25ad3780976f008c2bb7609796c86b9e53f?context=explore

I might be missing something, but its an interesting thing.
Also I could pull (the same) image with the different digest:
```
[root@jenkins ~]# docker image ls --digests
REPOSITORY                                                       TAG                  DIGEST                                                                    IMAGE ID       CREATED        SIZE
jenkins/jenkins                                                  lts-alpine           sha256:69ab567f0323544d0eaed78f1991dfb64a5fed95a4100264d68e5f99073ba9ee   447f5f160722   18 hours ago   247MB
jenkins/jenkins                                                  2.401.3-lts-alpine   sha256:21531ce1823b0410260f3ad0fce8fd5fdbc10056595cd46f89a5671cea0af480   73b4013cbb8f   3 weeks ago    258MB
jenkins/jenkins                                                  2.401.3-lts-alpine   sha256:d404158eae77dfbbbd642adfcccaa25ad3780976f008c2bb7609796c86b9e53f   73b4013cbb8f   3 weeks ago    258MB
```

**Comment by timja** [comment] 2023-08-19 09:14
Duplicate of https://github.com/jenkinsci/docker/issues/1690

**Closed by timja** 2023-08-19 09:14 UTC
Labels: triage, dockerhub
