### ISSUE TITLE
Artifacts proxy does not deliver incremental jars

### ISSUE THREAD

**Issue by uhafner** [jenkins-infra/helpdesk#3957] opened 2024-02-23 14:08 UTC
### Service(s)

Artifact-caching-proxy

### Summary

In my PR https://github.com/jenkinsci/warnings-ng-plugin/pull/1679 I am consuming several incremental artifacts from https://repo.jenkins-ci.org/incrementals. This works well for plugins (hpi extension) but not for java artifacts (jar extension). 

Here I get an error:

```
[INFO] --------------------------------[ hpi ]---------------------------------
14:27:13  [WARNING] The POM for io.jenkins.plugins:analysis-model-api:jar:12.0.0-rc794.1a_384a_2a_5d0b_ is missing, no dependency information available
14:27:13  [WARNING] The POM for io.jenkins.plugins:plugin-util-api:jar:3.9.0-rc894.7431fa_59180b_ is missing, no dependency information available
14:27:19  [WARNING] The POM for io.jenkins.plugins:forensics-api:jar:2.4.0-rc1565.4c3ec58d800d is missing, no dependency information available
14:27:25  [WARNING] The POM for edu.hm.hafner:analysis-model:jar:tests:12.0.0-rc5530.34264741ccf1 is missing, no dependency information available
14:27:28  [WARNING] The POM for io.jenkins.plugins:plugin-util-api:jar:tests:3.9.0-rc894.7431fa_59180b_ is missing, no dependency information available
14:28:12  [INFO] ------------------------------------------------------------------------
14:28:12  [INFO] Reactor Summary:
14:28:12  [INFO] 
14:28:12  [INFO] Warnings Plugin 11.0.0-SNAPSHOT .................... FAILURE [01:07 min]
14:28:12  [INFO] UI Tests of Warnings Plugin UNVERSIONED ............ SKIPPED
14:28:12  [INFO] Aggregator for Warnings Plugin UNVERSIONED ......... SKIPPED
14:28:12  [INFO] ------------------------------------------------------------------------
14:28:12  [INFO] BUILD FAILURE
14:28:12  [INFO] ------------------------------------------------------------------------
14:28:12  [INFO] Total time:  02:20 min
14:28:12  [INFO] Finished at: 2024-02-[23](https://ci.jenkins.io/job/Plugins/job/warnings-ng-plugin/job/PR-1679/19/pipeline-console/?start-byte=0&selected-node=53#log-23)T13:28:12Z
14:28:12  [INFO] ------------------------------------------------------------------------
14:28:12  [ERROR] Failed to execute goal on project warnings-ng: Could not resolve dependencies for project io.jenkins.plugins:warnings-ng:hpi:11.0.0-SNAPSHOT: The following artifacts could not be resolved: io.jenkins.plugins:analysis-model-api:jar:12.0.0-rc794.1a_384a_2a_5d0b_ (absent), io.jenkins.plugins:plugin-util-api:jar:3.9.0-rc894.7431fa_59180b_ (absent), io.jenkins.plugins:forensics-api:jar:2.4.0-rc1565.4c3ec58d800d (absent), edu.hm.hafner:analysis-model:jar:tests:12.0.0-rc5530.34[26](https://ci.jenkins.io/job/Plugins/job/warnings-ng-plugin/job/PR-1679/19/pipeline-console/?start-byte=0&selected-node=53#log-26)4741ccf1 (absent), io.jenkins.plugins:plugin-util-api:jar:tests:3.9.0-rc894.7431fa_59180b_ (absent): Could not find artifact io.jenkins.plugins:analysis-model-api:jar:12.0.0-rc794.1a_384a_2a_5d0b_ in azure-proxy (https://repo.azure.jenkins.io/public/) -> [Help 1]
14:[28](https://ci.jenkins.io/job/Plugins/job/warnings-ng-plugin/job/PR-1679/19/pipeline-console/?start-byte=0&selected-node=53#log-28):12  org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project warnings-ng: Could not resolve dependencies for project io.jenkins.plugins:warnings-ng:hpi:11.0.0-SNAPSHOT: The following artifacts could not be resolved: io.jenkins.plugins:analysis-model-api:jar:12.0.0-rc794.1a_384a_2a_5d0b_ (absent), io.jenkins.plugins:plugin-util-api:jar:3.9.0-rc894.7431fa_59180b_ (absent), io.jenkins.plugins:forensics-api:jar:2.4.0-rc1565.4c3ec58d800d (absent), edu.hm.hafner:analysis-model:jar:tests:12.0.0-rc55[30](https://ci.jenkins.io/job/Plugins/job/warnings-ng-plugin/job/PR-1679/19/pipeline-console/?start-byte=0&selected-node=53#log-30).34264741ccf1 (absent), io.jenkins.plugins:plugin-util-api:jar:tests:3.9.0-rc894.74[31](https://ci.jenkins.io/job/Plugins/job/warnings-ng-plugin/job/PR-1679/19/pipeline-console/?start-byte=0&selected-node=53#log-31)fa_59180b_ (absent): Could not find artifact io.jenkins.plugins:analysis-model-api:jar:12.0.0-rc794.1a_[38](https://ci.jenkins.io/job/Plugins/job/warnings-ng-plugin/job/PR-1679/19/pipeline-console/?start-byte=0&selected-node=53#log-38)4a_2a_5d0b_ in azure-proxy (https://repo.azure.jenkins.io/public/)
```

The same hpi artifacts are successfully delivered. The artifacts are correctly published under https://repo.jenkins-ci.org/incrementals/io/jenkins/plugins/forensics-api/2.4.0-rc1565.4c3ec58d800d/. A similar GitHub workflow that uses no proxy succeeds, see https://github.com/jenkinsci/warnings-ng-plugin/pull/1679/checks.

Do we filter incremental artifacts by extension in our proxy?

**Comment by lemeurherve** [comment] 2024-02-28 23:25
The only thing I can add for now is the content of the settings.xml we're using for ACP (that's a template but you'll get the gist of it):
https://github.com/jenkins-infra/jenkins-infra/blob/production/dist/profile/templates/jenkinscontroller/casc/artifact-caching-proxy.yaml.erb

I don't know yet if the issue is related or not to the addition of the plugin repositories profile: https://github.com/jenkins-infra/jenkins-infra/pull/3041/files

**Comment by dduportal** [comment] 2024-03-28 09:06
For info, we changed the behavior of the Artfact Caching Proxy ("ACP") in https://github.com/jenkins-infra/helpdesk/issues/3969 earlier today with a new 1.0.0 version.

This 1.0.0 feature a new resolution mechanism: ACP now tries to get the requested artifact from Jenkins public or falls back to Jenkins incremental and then Maven central. It implies a change in the settings.xml to unify to only "1 mirror".

It means Maven no longer retry on multiple mirrors (e.g. resolution has different implementation when using ACP on ci.jenkins.io compared to developer workstation) but ACP does with the same order.


@uhafner could you retry (as the PR was merged and it was quite some time ago) to see if the new behavior works as expected? We see incremental artifacts being available (and cached except the maven-metadata.xml) by ACP instances now so it should work better to your expectation

**Comment by uhafner** [comment] 2024-03-31 09:19
I'm not sure if this is related, but two of my builds fail with a strange error that indicates that a maven artifact is not found:

- https://ci.jenkins.io/job/Plugins/job/analysis-model/job/PR-1039/1/pipeline-console/?selected-node=33
- https://ci.jenkins.io/job/Plugins/job/analysis-model/job/PR-1035/3/pipeline-console/?selected-node=41

**Comment by dduportal** [comment] 2024-04-03 07:14
Hello @uhafner @MarkEWaite , the problem *should* be fixed. https://ci.jenkins.io/job/Plugins/job/analysis-model/job/PR-1039/2/ is now passing.

Can you check if you can reproduce the "incrementals not in ACP" behavior (e.g. the original subject of this issue)?

**Comment by dduportal** [comment] 2024-04-09 08:47
It looks like this issue is resolved as per https://github.com/jenkins-infra/helpdesk/issues/4021#issuecomment-2037954333.

As such I am closing the issue. Thanks all!

Please feel free to reopen if I am mistaken or if the problem re-surface.

**Closed by dduportal** 2024-04-09 08:47 UTC
Labels: artifact-caching-proxy
