### ISSUE TITLE
`pkg.origin.jenkins.io` SSL certificate expires Mar 28, 2023

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3446] opened 2023-03-14 00:23 UTC
### Service(s)

pkg.jenkins.io

### Summary

The SSL certificate for https://pkg.jenkins.io has a reasonable expiration of May 2023.

The SSL certificate for https://pkg.origin.jenkins.io expires before the end of March 2023.

I don't know the locations that depend on the SSL certificate of https://pkg.origin.jenkins.io .  For some reason, I added SSL monitoring for that certificate some years ago.  Unfortunately, I can't find notes that tell me why I added that check.

### Reproduction steps

1. Open https://pkg.origin.jenkins.io and check the certificate expiration as reported by the web browser.  My Chrome browser shows it will expire before the end of March 2023.

**Comment by dduportal** [comment] 2023-03-17 16:48
Reporting on diagnostic of this issue:

- Confirmed that the certificate should have been already renewed. Your monitoring is really usefull and we shall add it to our datadog to alert through pagerduty 
- Trying to renew manually the certificates on the VM:
  - The puppet module managing letsencrypt uses a crontab installed as root (as per [The puppet's LetEncrypt default setup on the Jenkins infrastructure](https://github.com/jenkins-infra/jenkins-infra/blob/df3b56e3949513d356818f19c91b9f92d7b86b64/hieradata/common.yaml#L89-L91))
  - The crontab is installed properly and specifies the `certbot renew -q` command as expected
  - The command `certbot renew`, when executed manually as `root` on the machine, errors with messages looking lik `Failed to renew xxxx with error: The requested apache plugin does not appear to be installed`
- The error points to the fact that `certbot` does not have the required module installed to allow it managing Apache (ti present the HTTP challenge and to reload configuration once a new certificate is present)
  - Confirmed with a `certbot plugins | grep -i -c apache` which responds `0`
  
=> The root cause is https://github.com/jenkins-infra/jenkins-infra/pull/2659 which changed the installation method of certbot by merging the "legacy" (apt) and "new but broken" (snap) into a pip packaging (with Python 3.8).

**Comment by dduportal** [comment] 2023-03-17 16:48
=> operating on this machine to see if adding the https://pypi.org/project/certbot-apache/ package is sufficient.

- Puppet disabled

**Comment by dduportal** [comment] 2023-03-17 17:05
- Did a backup of the `/etc/letsencrypt` before proceeding
- Confirmed that "only" adding the pip package `certbot-apache` allowed to renew (manually) the certificate properly. New date is `Thu, 15 Jun 2023 16:00:37 GMT`
- Discovered that the `pkg.origin.jenkins.io` domain is still configured in this VM, which fails to renew it has it's managed in fastly.

=> Incoming PR in puppet to fix this issue + remove the `pkg.origin.io` domain from renewal

**Comment by dduportal** [comment] 2023-03-17 19:50
- https://github.com/jenkins-infra/jenkins-infra/pull/2692 had been tested, merged and deployed
- https://github.com/jenkins-infra/jenkins-infra/pull/2693 fixed it up (puppet syntactic sugar)
- https://github.com/jenkins-infra/jenkins-infra/pull/2694 to ensure that `certbot-apache` plugin installs properly

**Closed by dduportal** 2023-03-17 19:50 UTC
Labels: certificate, pkg.jenkins.io, pkg.origin.jenkins.io
