### ISSUE TITLE
request reset of password for my jenkins account

### ISSUE THREAD

**Issue by vimil** [jenkins-infra/helpdesk#2796] opened 2022-02-24 11:59 UTC
### Service

Accounts

### Summary

Could you help me redet the password for my jenkins account. my email is vimilsaju@yahoo.com.
I tried resetting using https://accounts.jenkins.io but I did not receive any password reset email.

**Comment by timja** [comment] 2022-02-24 12:14
Duplicate of https://github.com/jenkins-infra/helpdesk/issues/2794

**Closed by timja** 2022-02-24 12:14 UTC
Labels: triage
