### ISSUE TITLE
Replace Blue Ocean in default display URL (or remove the Blue Ocean plugins)

### ISSUE THREAD

**Issue by uhafner** [jenkins-infra/helpdesk#2833] opened 2022-03-17 10:15 UTC
### Service(s)

ci.jenkins.io

### Summary

All our plugin builds on [ci.jenkins.io ](https://ci.jenkins.io/job/Plugins) use GitHub checks to report builds results directly in pull requests. The checks provide a details URL in the pull request to directly navigate to the results in Jenkins. Currently, the display URL of the Jenkins instance is shown here. However, this details URL currently is configured to show the Blue Ocean view in Jenkins rather than the classic Jenkins view. Can you please change that so that the Blue Ocean view is not shown by default anymore. (In my opinion we can remove Blue Ocean totally, as this project has been abandoned years ago.) 

(And yes: I know that I can customize the URL when logged in. But this is the main entry point for PR contributors and they should actually see Jenkins without logging in by using the current version without struggling with the deprecated Blue Ocean views.)

### Reproduction steps

Example:
- General URL: https://github.com/jenkinsci/code-coverage-api-plugin/pull/324/checks?check_run_id=5527265599 (bottom link points to https://ci.jenkins.io/job/Plugins/job/code-coverage-api-plugin/job/PR-324/10/display/redirect)
- Warnings URL: https://github.com/jenkinsci/code-coverage-api-plugin/pull/324/checks?check_run_id=5527345621 (bottom link points to https://ci.jenkins.io/job/Plugins/job/code-coverage-api-plugin/job/PR-324/10/pmd)

**Comment by dduportal** [comment] 2022-03-17 11:19
🤔  I assume that removing BlueOcean would solve the URL problem, but can't be sure. We might want to try on release.ci or infra.ci.

This is a good point that you make given the state of BlueOcean.
(Personnaly it will be hard for me to not have Blue Ocean. The Jenkins "classic" UI is barely usable for viewing pipelines but maybe I should start learning to use the pipeline graph view from Tim).

**Comment by timja** [comment] 2022-03-17 11:50
Pipeline graph is very much WIP and really needs someone with more time to look into it.

blueocean had a whole team of people to build it...

**Comment by dduportal** [comment] 2022-03-17 13:05
I have no idea how to setup the URL of the GitHub checks, in the scenario of "keeping BlueOcean". Where should I look? (e.g. is it the "check" plugin, or th" github check" plugin, or "github" or jenkins management page, or something else)

**Comment by KalleOlaviNiemitalo** [comment] 2022-03-17 15:48
The implementation rereads the property every time, so if you call `System.setProperty('jenkins.displayurl.provider', 'org.jenkinsci.plugins.displayurlapi.ClassicDisplayURLProvider')` in the script console, then that should take effect immediately. Unless the HTTP redirect response is cached somewhere.

**Comment by timja** [comment] 2022-03-17 15:55
I think this should probably be discussed on the mailing list.

**Comment by basil** [comment] 2022-03-20 17:19
+1 from me for changing the default from Blue Ocean to the standard UI. I almost always switch from Blue Ocean to the standard UI, so this would save me a click. I still do use Blue Ocean occasionally when I need to read the console log of a build with parallel stages, so I do not think we should remove the Blue Ocean plugin yet.

**Comment by dduportal** [comment] 2022-04-21 16:53
Delaying this issue due to not enough bandwidth.

**Comment by dduportal** [comment] 2022-05-03 09:51
- Email sent: https://groups.google.com/g/jenkinsci-dev/c/JIRBk42NXag
- Many thanks for the pointers @KalleOlaviNiemitalo ! @smerle33 from the team is currently working on preparing the change (even if contributors vote to not to) so we are prepared.

**Comment by dduportal** [comment] 2022-05-09 08:15
We've not seen any "no" answer (here and mailing list). Since this change is revertable, we'll proceed to apply it.

**Comment by dduportal** [comment] 2022-05-09 09:44
Change appplied successfully (and automatically) on ci.jenkins.io. Many thanks @smerle33 .

Check: https://github.com/jenkins-infra/pipeline-library/runs/6349066600 => click on the link `View more details on ci.jenkins.io` redirects to https://ci.jenkins.io/job/Infra/job/pipeline-library/job/master/255/ which is the classic UI.

**Comment by KalleOlaviNiemitalo** [comment] 2022-05-09 10:21
Huh, that link doesn't even redirect; rather, it points directly to the classic UI. So if this change is ever reverted, then these links on GitHub will keep pointing to the classic UI.

**Comment by timja** [comment] 2022-05-09 10:29
the GitHub links will still use the display/redirect url. 

Which depending on the instance setting and the per user setting will redirect to either blue ocean, pipeline graph view or classic

**Comment by KalleOlaviNiemitalo** [comment] 2022-05-09 10:37
There is no `display/redirect` suffix at <https://github.com/jenkins-infra/pipeline-library/runs/6349066600>:

```HTML
<a class="text-small color-fg-muted" target="_blank" rel="noopener noreferrer" data-hydro-click="{&quot;event_type&quot;:&quot;check_suite.external_click&quot;,&quot;payload&quot;:{&quot;check_suite_id&quot;:6426637249,&quot;check_run_id&quot;:6349066600,&quot;link_url&quot;:&quot;https://ci.jenkins.io/job/Infra/job/pipeline-library/job/master/255/&quot;,&quot;link_text&quot;:&quot;View more details on&quot;,&quot;originating_url&quot;:&quot;https://github.com/jenkins-infra/pipeline-library/runs/6349066600&quot;,&quot;user_id&quot;:46201428}}" data-hydro-click-hmac="9b597c7bbadefda29921b5c3f227af3ad4cdd0cb1fb15a127f82b04226817337" href="https://ci.jenkins.io/job/Infra/job/pipeline-library/job/master/255/">
          <svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true" class="octicon octicon-link-external mr-2">
    <path fill-rule="evenodd" d="M10.604 1h4.146a.25.25 0 01.25.25v4.146a.25.25 0 01-.427.177L13.03 4.03 9.28 7.78a.75.75 0 01-1.06-1.06l3.75-3.75-1.543-1.543A.25.25 0 0110.604 1zM3.75 2A1.75 1.75 0 002 3.75v8.5c0 .966.784 1.75 1.75 1.75h8.5A1.75 1.75 0 0014 12.25v-3.5a.75.75 0 00-1.5 0v3.5a.25.25 0 01-.25.25h-8.5a.25.25 0 01-.25-.25v-8.5a.25.25 0 01.25-.25h3.5a.75.75 0 000-1.5h-3.5z"></path>
</svg>View more details on ci.jenkins.io
</a>
```

**Comment by timja** [comment] 2022-05-09 10:45
Interesting you're right.

something is wrong here.

I set my preferences to be blue ocean and I didn't get sent there. =/

**Comment by KalleOlaviNiemitalo** [comment] 2022-05-09 11:01
It might be best to revert this for now, and file a bug on display-url-api-plugin

**Comment by dduportal** [comment] 2022-05-09 11:18
https://github.com/jenkins-infra/jenkins-infra/pull/2163 to revert

**Comment by KalleOlaviNiemitalo** [comment] 2022-05-09 12:33
DisplayURLProvider.DisplayURLProviderImpl overrides methods to append DISPLAY_POSTFIX = "display/redirect", and classes like RunDisplayAction then call AbstractDisplayAction.lookupProvider(StaplerRequest) to choose the provider that selects the redirect URL. But if the jenkins.displayurl.provider property points to org.jenkinsci.plugins.displayurlapi.ClassicDisplayURLProvider, then DisplayURLProvider.DisplayURLProviderImpl is not used and does not get a chance to add DISPLAY_POSTFIX.

**Comment by dduportal** [comment] 2022-05-10 13:45
@KalleOlaviNiemitalo do you mind opening an issue on the plugin tracker?

**Comment by KalleOlaviNiemitalo** [comment] 2022-05-10 13:59
@dduportal I don't currently have an instance in which I could safely verify the incorrect behavior.

**Comment by dduportal** [comment] 2022-07-13 13:52
> @dduportal I don't currently have an instance in which I could safely verify the incorrect behavior.

Fair, but I have no idea which plugin, which tracker it is (I'm not a Java developer) so I need your help on this to at least open the issue in the correct location

**Comment by timja** [comment] 2023-08-19 09:25
FYI the issue that prevented this change was fixed in https://github.com/jenkinsci/display-url-api-plugin/releases/tag/display-url-api-2.3.9

**Comment by RosenKaramanov** [comment] 2024-03-19 13:04
this fix did not help for me, any other ideas? its quite annoying

**Comment by timja** [comment] 2024-03-19 15:08
> this fix did not help for me, neither any of the provided workarounds. Any other ideas? its quite annoying

Can you explain steps to reproduce?

**Comment by timja** [comment] 2024-05-08 15:17
+1 from me

**Comment by NotMyFault** [comment] 2024-05-08 15:19
+1

**Comment by dduportal** [comment] 2024-05-08 16:10
+1

**Comment by lemeurherve** [comment] 2024-05-10 17:26
Change applied on infra.ci.jenkins.io and weekly.ci.jenkins.io but rollbacked on ci.jenkins.io as I encountered the following error:

![image](https://github.com/jenkins-infra/helpdesk/assets/91831478/754376d0-13fd-42f6-aa04-23e754e968a5)

**Comment by dduportal** [comment] 2024-05-29 11:15
Deferring issue to the 2024-06-11 milestone, time for Jay to get ready around JCasc.

**Comment by dduportal** [comment] 2024-06-10 14:36
Update:

- @jayfranco999 was able to reproduce the JCasc error from @lemeurherve last try, on his local vagrant VM
- The issue was related to indentation in the JCasc YAML file generated by Puppet templates
- PR https://github.com/jenkins-infra/jenkins-infra/pull/3465 opened with a fix: we plan to deploy it to ci.jenkins.io Tuesday morning (between 07:00am and 08:00am UTC)

**Comment by dduportal** [comment] 2024-06-11 11:42
Update:

- PR https://github.com/jenkins-infra/jenkins-infra/pull/3468 was deployed with succes. It required 2 hotfixes:
 - https://github.com/jenkins-infra/jenkins-infra/commit/ded57785b6bcd9326140b88febc93d0cdf1e3f41 => as the PR forgot to update the ci.jio hieradata (only vagrant's) 
 -  https://github.com/jenkins-infra/jenkins-infra/commit/dc673c579eddc81c604638b53b2e6d1f506a0dd7 => overcomes a hierdata YAML engine weird indentation behavior which most probably also bit @lemeurherve on last attempt


ci.jenkins.io is also set up with the specified setting: we can close.

Congrats @jayfranco999 on your first finished issue!

**Closed by dduportal** 2024-06-11 11:42 UTC
Labels: ci.jenkins.io

**Comment by dlarr** [comment] 2024-11-12 16:10
Hello, 

I maintain a sharedlib to build my ~1000 projects (on bitbucket), they are dispatched on ~100 different Jenkins. 
These Jenkins have this plugin on 2.3.5 version. 

I don't wish to set my prefered view on each Jenkins. And also I don't want to set the provider like so : `System.setProperty('jenkins.displayurl.provider', 'org.jenkinsci.plugins.displayurlapi.ClassicDisplayURLProvider')`

Because I don't want to impact other sharedlib scopes.

I would like to be able to impact the link sent to bitbucket builds in a way like that: 
`env.JOB_DISPLAY_URL = env.BUILD_URL // <= This doesn't seems to work.`

so that 
* This simple variable (or plugin call ?) impacts all 100 Jenkins at once ?
* This simple variable (or plugin call ?) does not impact other sharedlib ? 

 Can you please tell me if there is a way to achieve this ?
