### ISSUE TITLE
"Mirror Status" link from get.jenkins.io returns a 404 error

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#3790] opened 2023-10-18 10:36 UTC
### Service(s)

get.jenkins.io

### Summary

The last "Mirror Status" link from https://get.jenkins.io/ returns a 404 error.

https://get.jenkins.io/status.html redirects to https://ftp-nyc.osuosl.org/pub/jenkins/status.html, error 404.

**Comment by dduportal** [comment] 2023-11-14 13:00
After a few checks:

- No mirror has the `status.html` file as per https://get.jenkins.io/status.html?mirrorlist
- Exception of archives.jenkins.io (which is not really a mirror today): https://archives.jenkins.io/status.html
- It appears that this page is a remnant of the old system "mirrorbrain" we used on the pkg VM way before mirrorbits.

=> I'm gonna remove the file from get.jenkins.io,  archives.jenkins.io and update the link.

**Comment by dduportal** [comment] 2023-11-14 13:15
Update:

- File `status.html` removed (I got  a local backup just in case)
- Updated the get.jenkins.io's `index.html` file to remove the `status` link: it is not visible anymore
- Let's wait for the 2.432 release to be packaged to see if the file is regenerated by a template or kept as it

**Comment by dduportal** [comment] 2023-11-14 14:13
Closing as the problem is solved!

**Closed by dduportal** 2023-11-14 14:13 UTC
Labels: get.jenkins.io, osuosl
