### ISSUE TITLE
Out of space on a ci.jenkins.io agent in bom build

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3423] opened 2023-03-06 02:24 UTC
### Service(s)

ci.jenkins.io

### Summary

One of the tests in a recent build of the plugin bill of materials master branch failed due to insufficient space.  See the failure in the [log file](https://ci.jenkins.io/job/Tools/job/bom/job/master/1497/testReport/junit/(root)/InjectedTest/pct_git_weekly___testPluginActive/)

The plugin bill of materials now includes the AWS SDK plugins.  They are quite large, so they may have exceeded the disc space available on the agent or container.

### Reproduction steps

1. Review the [log file](https://ci.jenkins.io/job/Tools/job/bom/job/master/1497/testReport/junit/(root)/InjectedTest/pct_git_weekly___testPluginActive/) and another [log file](https://ci.jenkins.io/job/Tools/job/bom/job/master/1507/testReport/org.jvnet.hudson.test/PluginAutomaticTestBuilder$OtherTests/pct_structs_2_361_x___testPluginActive/) and another [log file](https://ci.jenkins.io/job/Tools/job/bom/job/master/1506/testReport/junit/org.jvnet.hudson.test/PluginAutomaticTestBuilder$OtherTests/pct_structs_weekly___testPluginActive/)

**Comment by smerle33** [comment] 2023-03-09 14:17
this is the agent that was out of space : `[2023-03-06T00:52:58.729Z] Agent jnlp-maven-17-jr7j2 is provisioned from template jnlp-maven-17`

**Comment by MarkEWaite** [comment] 2023-03-09 14:59
Thanks very much @smerle33 !  I see another out of space message in this [recent log file](https://ci.jenkins.io/job/Tools/job/bom/job/PR-1840/2/testReport/(root)/InjectedTest/pct_resource_disposer_weekly___testPluginActive/).  Any recommendation on what needs to be changed in order to increase available disc space on the maven-17 agents?

**Comment by MarkEWaite** [comment] 2023-03-09 15:04
I used `replay` of the acceptance tests job to report the available disc space on a newly allocated `maven-17` agent.  The report is:

```
08:01:34  + df
08:01:34  Filesystem     1K-blocks     Used Available Use% Mounted on
08:01:34  overlay         20959212 13209700   7749512  64% /
08:01:34  tmpfs              65536        0     65536   0% /dev
08:01:34  tmpfs           32516896        0  32516896   0% /sys/fs/cgroup
08:01:34  shm                65536        0     65536   0% /dev/shm
08:01:34  /dev/nvme0n1p1  20959212 13209700   7749512  64% /etc/hosts
08:01:34  tmpfs            7812500       12   7812488   1% /run/secrets/kubernetes.io/serviceaccount
08:01:34  tmpfs           32516896        0  32516896   0% /proc/acpi
08:01:34  tmpfs           32516896        0  32516896   0% /sys/firmware
```

I think that 8 GB of free space on the file system is not enough for some of these jobs.  Can we increase it to 16 GB of free space?

**Comment by MarkEWaite** [comment] 2023-03-09 15:38
Surprising that `maven-17` is the smallest disc configuration.  The other configurations report the disc space as:

```
08:02:56  + df
08:02:56  Filesystem     1K-blocks     Used Available Use% Mounted on
08:02:56  overlay        206374320 36813076 161135792  19% /
08:02:56  tmpfs              65536        0     65536   0% /dev
08:02:56  tmpfs           16442188        0  16442188   0% /sys/fs/cgroup
08:02:56  shm                65536        0     65536   0% /dev/shm
08:02:56  /dev/vda1      206374320 36813076 161135792  19% /etc/hosts
08:02:56  tmpfs            7812500       12   7812488   1% /run/secrets/kubernetes.io/serviceaccount
08:02:56  tmpfs           16442188        0  16442188   0% /proc/acpi
08:02:56  tmpfs           16442188        0  16442188   0% /sys/firmware
```

**Comment by dduportal** [comment] 2023-03-09 17:28
> We want to use `emptyDir` for the workspace of course. This is the [default](https://github.com/jenkinsci/kubernetes-plugin/blob/73d36f3b9103e0dd348c7046675d2851192d4083/src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace/WorkspaceVolume.java#L47-L49).

Gotta check but I guess the `~/.m2` might be one of the potential culprits here. (I would even think about enabling read-only for layered FS and iterate from there by exhaustively defining the volumes but it might be too much :D )

**Comment by jglick** [comment] 2023-03-09 18:48
Ah yes, you want to run Maven with something like `-Dmaven.repo.local=$WORKSPACE_TMP/m2repo`. Core already does so as does `buildPlugin` but it looks like this was forgotten in `bom`. Let me try to fix that…

**Comment by jglick** [comment] 2023-03-09 19:19
I wonder if you could add to the agent containers something like

```dockerfile
RUN echo 'please run Maven with -Dmaven.repo.local=$WORKSPACE_TMP/m2repo' > /home/jenkins/.m2/repository
```

to cause containerized builds to fail predictably if they neglected to do this? Plugins would not be affected, so this would be for miscellaneous repos.

**Comment by dduportal** [comment] 2023-03-09 19:33
> I wonder if you could add to the agent containers something like
> 
> ```dockerfile
> RUN echo 'please run Maven with -Dmaven.repo.local=$WORKSPACE_TMP/m2repo' > /home/jenkins/.m2/repository
> ```
> 
> to cause containerized builds to fail predictably if they neglected to do this? Plugins would not be affected, so this would be for miscellaneous repos.

Yes, that might be a way. But i do not see any problems to mount this directory in another empty dir as well (eventually in read only for a fail fast 😆)

**Comment by jglick** [comment] 2023-03-09 22:03
Should be fixed now at least for `bom`.

**Comment by MarkEWaite** [comment] 2023-03-10 00:31
The change from @jglick is applied to the master branch in [build 1508](https://ci.jenkins.io/job/Tools/job/bom/job/master/1508/changes).  Unfortunately, one of the tests fails with ["out of space"](https://ci.jenkins.io/job/Tools/job/bom/job/master/1508/testReport/junit/org.jvnet.hudson.test.junit/FailedTest/pct_durable_task_weekly___org_jvnet_hudson_test_JellyTestSuiteBuilder$JellyTestSuite/) on that run as well.

* [Build 1506](https://ci.jenkins.io/job/Tools/job/bom/job/master/1506/testReport/junit/org.jvnet.hudson.test/PluginAutomaticTestBuilder$OtherTests/pct_structs_weekly___testPluginActive/) - out of space in `/tmp/jenkins4553988105150476528` (before the change)
* [Build 1507](https://ci.jenkins.io/job/Tools/job/bom/job/master/1507/testReport/org.jvnet.hudson.test/PluginAutomaticTestBuilder$OtherTests/pct_structs_2_361_x___testPluginActive/) - out of space in `/home/jenkins/agent/workspace/Tools_bom_master` (before the change)
* [Build 1508](https://ci.jenkins.io/job/Tools/job/bom/job/master/1508/testReport/org.jvnet.hudson.test.junit/FailedTest/pct_durable_task_weekly___org_jvnet_hudson_test_JellyTestSuiteBuilder$JellyTestSuite/) - out of space in `/home/jenkins/agent/workspace/Tools_bom_master` (after the change)

It seems like some other change will be needed as well.

I've merged the master branch into PR-1840 and am letting it run as [build 3](https://ci.jenkins.io/job/Tools/job/bom/view/change-requests/job/PR-1840/3/testReport/)

**Comment by jglick** [comment] 2023-03-10 11:55
> PR-1840

https://github.com/jenkinsci/bom/pull/1840 that is

**Comment by MarkEWaite** [comment] 2023-03-17 01:47
Another failure due to out of space on a recent bom build:

https://ci.jenkins.io/job/Tools/job/bom/job/PR-1867/1/testReport/(root)/InjectedTest/pct_subversion_2_361_x___testPluginActive/

We're falling behind on BOM merges because the jobs are not completing successfully.  Out of space errors or job timeout errors have limited us to only 2 or 3 merges in the last several days, with a queue of 19 pull requests waiting to be merged.

**Comment by dduportal** [comment] 2023-03-17 10:44
Pair debugging session with @lemeurherve: 

- As explained by @jglick , we alos see the empty dir on the agent workdir (`/home/jenkins/agent`) as expected
- The full disk on `/home/jenkins/agent` seems to only happens on the `cik8s` cluster: it is an AWS EKS cluster and we saw that the underlying node filesystem is 20 Go only (with both the overlays, and emptydirs in it)
  - Short term: let's use only doks for the BOm build to unblock the merge train
  - Long term: Jenkins infra team will search and and fix the EKS nodepools to get enough disk spaces on the underlying machines
- The full disk on `/tmp` allowed us to see that `/tmp` is an overlay filesystem. it is not sustainable (I/O performances are poooor). We have to either use it as a real `tmpfs` or as an (another) emptyDir.
- Another point raised by both @smerle33 and @lemeurherve when diagnosing: the `/home/jenkins` directory should also be an(other) emptyDir mount as process might have to write stuff within

**Comment by dduportal** [comment] 2023-03-17 16:58
With https://github.com/jenkins-infra/aws/pull/361, the size of the local nodes for AWS EKS's `cik8s` went from `20Gb` to 200Gb as confirmed by a job replay (https://ci.jenkins.io/blue/organizations/jenkins/Tools%2Fbom/detail/PR-1867/4/pipeline/4):

```bash
[2023-03-17T16:49:39.294Z] + df -h /
[2023-03-17T16:49:39.294Z] Filesystem      Size  Used Avail Use% Mounted on
[2023-03-17T16:49:39.294Z] overlay         200G   15G  186G   8% /
```
```bash
[2023-03-17T16:49:40.460Z] + df -h ./
[2023-03-17T16:49:40.460Z] Filesystem      Size  Used Avail Use% Mounted on
[2023-03-17T16:49:40.460Z] /dev/nvme0n1p1  200G   15G  186G   8% /home/jenkins/agent
```

**Comment by lemeurherve** [comment] 2023-03-17 17:05
For the record, in https://github.com/jenkins-infra/aws/pull/361 we've also modified the EBS volume type from `gp2` to `gp3`, and increased the IOPS from 100 to 3000.

Next steps: check the consumed space by the BOM builds to potentially decrease the nodes disk size as 200GB might be too much and too costly.

**Comment by dduportal** [comment] 2023-03-22 13:31
> (PCT builds should also not generally be writing anything significant to `/home/jenkins` outside the configured workspace directory.)

That is a good practise 👍  But the pod templates are defined at the administrator level so other project could use it (and ensuring all the projects are not writing in the `$HOME` would be time consuming.

Enabling the `read-only` mode for the overlay would help a lot to catch such cases though

**Comment by jglick** [comment] 2023-03-22 15:17
> Enabling the `read-only` mode for the overlay

Seems draconian when some tools might just write a tiny config file or something to `$HOME`. I think you just need to block use of `~/.m2/repository` (or make it an emptydir).

**Comment by dduportal** [comment] 2023-03-22 16:24
> > Enabling the `read-only` mode for the overlay
> 
> Seems draconian when some tools might just write a tiny config file or something to `$HOME`. I think you just need to block use of `~/.m2/repository` (or make it an emptydir).

The `read-only` would only be with the `$HOME` set up as an empty dir.
The main reason, is that I/O performances are really really bad in the overlay filesystem: the read-only ensures that never ever the "bad I/O performances" case is met.

**Closed** 2023-04-11 10:40 UTC
Labels: ci.jenkins.io
