### ISSUE TITLE
pkg.jenkins.io certificate expired - varnish cache reports

### ISSUE THREAD

**Issue by mattboothman** [jenkins-infra/helpdesk#2957] opened 2022-05-27 19:03 UTC
### Service(s)

pkg.jenkins.io

### Summary

I'm trying to install jenkins but getting a certificate expired response from pkg.jenkins.io varnish cache

### Reproduction steps

```
 curl https://pkg.jenkins.io/debian-stable/jenkins.io.key

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 certificate has expired</title>
  </head>
  <body>
    <h1>Error 503 certificate has expired</h1>
    <p>certificate has expired</p>
    <h3>Error 54113</h3>
    <p>Details: cache-man4127-MAN 1653674845 1128735928</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

Not sure if dns info might help?

```
;; ANSWER SECTION:
pkg.jenkins.io.         2586    IN      CNAME   dualstack.d.sni.global.fastly.net.
dualstack.d.sni.global.fastly.net. 6 IN A       151.101.2.133
dualstack.d.sni.global.fastly.net. 6 IN A       151.101.66.133
dualstack.d.sni.global.fastly.net. 6 IN A       151.101.130.133
dualstack.d.sni.global.fastly.net. 6 IN A       151.101.194.133
```

**Comment by dduportal** [comment] 2022-05-27 21:13
Many thanks for reporting.

This issue is a consequence of #2888 . Sorry for the inconvenience.

Reported on https://github.com/jenkins-infra/status/pull/168 for status.jenkins.io.

We are working on it.

**Comment by dduportal** [comment] 2022-05-27 21:25
After https://github.com/jenkins-infra/jenkins-infra/pull/2188, the problem should be solved.

Just tried to install successfull on Ubuntu 20.04 and centos 7. Is it working for you now?

**Comment by MarkEWaite** [comment] 2022-05-27 23:19
The SSL certificate is correct but when I attempt to install or update a Debian package, it fails with the message:

```
Redirection from https to 'http://mirrors.jenkins.io/debian/jenkins_2.349_all.deb' is forbidden
```

The failure is visible on the Debian and Debian stable acceptance test jobs on ci.jenkins.io.  See

* [Weekly Debian install job](https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/install-latest-debian-package/)
* [LTS Debian install job](https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/install-lts-debian-package/)

I see the same message on a locally installed Debian 10 and a locally installed Debian 11.

Surprisingly, the Red Hat package installers work as expected.

**Comment by halkeye** [comment] 2022-05-27 23:56
Redhat must not care, which doesn't seem good

https://github.com/jenkins-infra/jenkins-infra/blob/df1a23b54bce3328f7466dc4fb4623a1173925ab/dist/profile/templates/pkgrepo/debian_htaccess.erb#L16 <-- deb
https://github.com/jenkins-infra/jenkins-infra/blob/df1a23b54bce3328f7466dc4fb4623a1173925ab/dist/profile/templates/pkgrepo/redhat_htaccess.erb#L13 <-- rpm

**Comment by mattboothman** [comment] 2022-05-28 05:48
> After [jenkins-infra/jenkins-infra#2188](https://github.com/jenkins-infra/jenkins-infra/pull/2188), the problem should be solved.
> 
> Just tried to install successfull on Ubuntu 20.04 and centos 7. Is it working for you now?

All good now, thank you :-)

**Comment by mattboothman** [comment] 2022-05-28 05:53
Sorry, I spoke too soon. I can install the key but installing the package fails with:

```
Get:1 http://gb.archive.ubuntu.com/ubuntu focal/main amd64 net-tools amd64 1.60+git20180626.aebd88e-1ubuntu1 [196 kB]
Err:2 https://pkg.jenkins.io/debian-stable binary/ jenkins 2.332.3
  Redirection from https to 'http://mirrors.jenkins.io/debian-stable/jenkins_2.332.3_all.deb' is forbidden [IP: 151.101.194.133 443]
Fetched 196 kB in 3s (73.1 kB/s)
E: Failed to fetch https://pkg.jenkins.io/debian-stable/binary/jenkins_2.332.3_all.deb  Redirection from https to 'http://mirrors.jenkins.io/debian-stable/jenkins_2.332.3_all.deb' is forbidden [IP: 151.101.194.133 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

Same as @MarkEWaite got.

**Comment by mattboothman** [comment] 2022-05-28 06:10
The first request is redirected to `http`.

```
   curl -IL https://pkg.jenkins.io/debian-stable/binary/jenkins_2.332.3_all.deb
   
   HTTP/2 302
   server: Apache
>> location: http://mirrors.jenkins.io/debian-stable/jenkins_2.332.3_all.deb
   content-type: text/html; charset=iso-8859-1
   accept-ranges: bytes
   date: Sat, 28 May 2022 06:00:14 GMT
   via: 1.1 varnish
   age: 548
   x-served-by: cache-man4127-MAN
   x-cache: HIT
   x-cache-hits: 1
   x-timer: S1653717614.411058,VS0,VE0
   strict-transport-security: max-age=300
   content-length: 247
   
   HTTP/1.1 308 Permanent Redirect
   Date: Sat, 28 May 2022 06:00:14 GMT
   Content-Type: text/html
   Content-Length: 164
   Connection: keep-alive
>> Location: https://mirrors.jenkins.io/debian-stable/jenkins_2.332.3_all.deb
   
   HTTP/2 302
   date: Sat, 28 May 2022 06:00:14 GMT
   content-type: text/html; charset=utf-8
>> location: https://ftp.halifax.rwth-aachen.de/jenkins/debian-stable/jenkins_2.332.3_all.deb
   cache-control: private, no-cache
   link: <https://mirror.gruenehoelle.nl/jenkins/debian-stable/jenkins_2.332.3_all.deb>; rel=duplicate; pri=1; geo=nl
   strict-transport-security: max-age=86400; includeSubDomains; preload
   
   HTTP/2 200
   server: nginx/1.18.0
   date: Sat, 28 May 2022 06:00:15 GMT
   content-type: application/octet-stream
   content-length: 91433912
   last-modified: Wed, 04 May 2022 15:58:51 GMT
   accept-ranges: bytes
```

**Comment by DoxtorDoz** [comment] 2022-05-28 07:11
I had the same exact problem and I solved it with this:

`
wget https://pkg.jenkins.io/debian-stable/binary/jenkins_2.332.3_all.deb
sudo dpkg -i jenkins_2.332.3_all.deb
`

I installed that version because it was the first one that worked

**Comment by mattboothman** [comment] 2022-05-28 07:12
I did the same

**Comment by MarkEWaite** [comment] 2022-05-28 09:53
Thanks for the reminder that it is feasible to download the deb file as a workaround.

**Comment by dduportal** [comment] 2022-05-29 11:33
Many thanks for everyone involded in helping by reporting and proposing fixes!
Really sorry for the inconvniences that it caused to everyone.

Since https://github.com/jenkins-infra/jenkins-infra/pull/2192 and https://github.com/jenkins-infra/jenkins-infra/pull/2195 were applied, it looks like that it's working again. 

As my tests were not torough 2 days ago, let's wait for 2 days to confirm that it is back working for end-users.


Ping @mattboothman @DoxtorDoz @tianon if you have time to test and confirm on your end.

**Comment by OLEGSHA** [comment] 2022-05-29 11:36
I had the same issue just a couple hours ago and I can confirm that it is now fixed.

**Comment by MarkEWaite** [comment] 2022-05-29 12:43
I've confirmed that it is fixed in the two acceptance tests that run on ci.jenkins.io.

* [Weekly release](https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/install-latest-debian-package/)
* [LTS release](https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/install-lts-debian-package/)

Thanks @dduportal !

**Comment by DoxtorDoz** [comment] 2022-05-29 16:27
Now it's working so it's fixed, thanks @dduportal

**Comment by dduportal** [comment] 2022-05-30 08:57
Closing as it is confirmed fixed. Next outage: https://github.com/jenkins-infra/helpdesk/issues/2960 (service updates.jenkins.io on the same VM)

**Closed by dduportal** 2022-05-30 08:57 UTC
Labels: pkg.jenkins.io

**Comment by growell-nuan** [comment] 2023-04-03 12:56
Directions [here](https://pkg.jenkins.io/debian-stable/) need updating. Shows expired key signature.

**Comment by MarkEWaite** [comment] 2023-04-03 13:11
@growell-nuan this issue was not related to the PGP signing of deb packages and rpm packages.  It was related to the SSL certificate.

See https://www.jenkins.io/blog/2023/03/27/repository-signing-keys-changing/ for the blog post that announces the change of signing key and that the Debian stable package will be updated Wednesday, April 5, 2023 with the 2.387.2 release.

**Comment by growell-nuan** [comment] 2023-04-03 13:35
Wasn't confused about the fix. Was noting out-of-date directions on repository server.
