### ISSUE TITLE
Wrong plugin redirect

### ISSUE THREAD

**Issue by xnumad** [jenkins-infra/helpdesk#3791] opened 2023-10-12 19:14 UTC
### Problem with this page

https://wiki.jenkins-ci.org/display/JENKINS/Task+Scanner+Plugin

### Expected behavior

Get redirected to the plugin

### Actual behavior

Get redirected to
`http://wiki.jenkins-ci.org/"https://plugins.jenkins.io/warnings-ng/"`
and eventually (some further redirects) to
`https://google.com/search?q=site:jenkins.io "`

### Possible solution

Make it directly redirect to `https://plugins.jenkins.io/warnings-ng/` which seems to have been the intention here

**Comment by dduportal** [comment] 2023-10-21 16:54
It looks like the cause of this behavior is: https://github.com/jenkins-infra/docker-confluence-data/blob/77638c9414da21758dc2060ab65fe4c3e659f2ba/nginx/nginx.conf#L1454

**Comment by dduportal** [comment] 2023-10-21 17:14
Proposed fix in https://github.com/jenkins-infra/docker-confluence-data/pull/50, which, once released, will need to be deployed in production before the redirection is fixed

**Comment by dduportal** [comment] 2023-10-22 09:28
Hi @xnumad , thanks again for reporting this error! It also allowed us to catch the same kind of error on a few other pages.

It is now fixed (deployed in https://github.com/jenkins-infra/kubernetes-management/pull/4567):

```
$ curl --verbose https://wiki.jenkins-ci.org/display/JENKINS/Task+Scanner+Plugin 2>&1 | grep -i location
< location: https://plugins.jenkins.io/warnings-ng/
```

and the redirect looks good.

**Closed by dduportal** 2023-10-22 09:28 UTC
Labels: bug, plugin
