### ISSUE TITLE
A few SSL certificates expire in 17 days or less

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3748] opened 2023-09-10 13:19 UTC
### Service(s)

jenkins.io

### Summary

The SSL certificate for some our older domain names will expire 5 Oct 2023.  The HTTP servers with expiring certificates include:

* https://jenkins-ci.org
* https://www.jenkins-ci.org
* https://jenkins.io

### Reproduction steps

1. Use curl to report the SSL certificate expiration dates:
```bash
mwaite $ curl -vI https://jenkins-ci.org --stderr - | grep "expire"
*  expire date: Oct  5 13:27:48 2023 GMT

mwaite $ curl -vI https://www.jenkins-ci.org --stderr - | grep "expire"
*  expire date: Oct  5 13:27:48 2023 GMT

mwaite $ curl -vI https://jenkins.io --stderr - | grep "expire"
*  expire date: Oct  5 13:27:48 2023 GMT
```

**Comment by dduportal** [comment] 2023-09-11 10:59
For info: While working on https://github.com/jenkins-infra/helpdesk/issues/3351, we had to change back and forth the DNS record used for ACME validation for these domains:
- https://github.com/jenkins-infra/azure-net/pull/113
- https://github.com/jenkins-infra/azure-net/pull/115
- https://github.com/jenkins-infra/azure-net/pull/116

This is the most probable cause of non-renewal: either Fastly fails or our `publick8s` fails to renew certificate.

We might want to remove these domains from `publick8s` and fully delegate them to Fastly  but we have to check why/what/how

**Comment by dduportal** [comment] 2023-09-12 14:39
It looks like the problem is due to our `publick8s` AKS cluster:

- The 2 domains `jenkins-ci.org` and `www.jenkins-ci.org`  points to the publick8s whichis failing the Certificate renewal order (gotta add more logs)
- Same for he domain `jenkins.io`

Fastly only has the domain www.jenkins.io (other are redirecting to www.jenkins.io) but has ACME setup for both www.jenkins.io and jenkins.io.


It means we have to:

- Remove any ACME setup from Fastly to let the AKS `publick8s` to manage certificates and unblock the renewal
- Remove any setup for the `www.jenkins.io`  in the AKS `publick8s`  ingresses (as it points to Fastly which access the webservice as backend through `www.origin.jenkins.io`

**Comment by dduportal** [comment] 2023-09-13 06:45
Addition: lets use https://github.com/jenkins-infra/kubernetes-management/pull/4346, once the configuration is fixed, to regnerate certificates (the cert-manager new deployment will trigger CSRs again)

**Comment by dduportal** [comment] 2023-09-18 07:46
Update:

- Checked the Cert Manager order for the `jenkinsio` certificate on `publick8s` cluster: it is stuck at the `jenkins.io` domain phase, which confirms previous analysis (use https://cert-manager.io/docs/troubleshooting/ to get a better understanding)

- Removed the `jenkins.io` APEX domain (+ its certificate) from Fastly to have it fully managed by the AKS `publick8s` cluster because:
  - The DNS record `jenkins.io` points to the AKS `publick8s` cluster
  - There are no APEX redirect enabled on fastly for `jenkins.io` -> `www.jenkins.io`

- Removed the DNS `TXT` record `_acme-challenge` from the DNS zone `jenkins.io` as it was using a Fastly provided value
- Opened https://github.com/jenkins-infra/azure-net/pull/136 to ensure this record won't be recreated for Fastly usage (and only by cert-manager)

**Comment by dduportal** [comment] 2023-09-18 07:50
Update: 

- Removed the Cert Manager (stuck since 12 days) orders with a `kubectl delete order -n jenkinsio <order name>`
- A new order is re-created immediatly and went to completion (with DNS challenges created successfully).
- The ingress' secret `jenkinsio-tls` is updated with the following new validity:

  ```text
  Validity period:
        Not Before: Mon, 18 Sep 2023 06:33:51 UTC
        Not After: Sun, 17 Dec 2023 06:33:50 UTC
  ```

- Certificates are updated:

```
$ curl -vI https://jenkins-ci.org --stderr - | grep "expire"
*  expire date: Dec 17 06:33:50 2023 GMT

$ curl -vI https://www.jenkins-ci.org --stderr - | grep "expire"
*  expire date: Dec 17 06:33:50 2023 GMT

$ curl -vI https://jenkins.io --stderr - | grep "expire"
*  expire date: Dec 17 06:33:50 2023 GMT
* ```

**Comment by dduportal** [comment] 2023-09-18 07:52
I'm closing the issue:

- Certificates have been renewed by the automatic process
- The "problem" preventing the automatic renewal has been identified and fixed so it won't happen again

**Closed by dduportal** 2023-09-18 07:52 UTC
Labels: jenkins.io
