### ISSUE TITLE
Requests to mirrors.jenkins.io timing out

### ISSUE THREAD

**Issue by cinnion** [jenkins-infra/helpdesk#3653] opened 2023-07-09 16:47 UTC
### Service(s)

Other

### Summary

While pingable, requests to the mirror redirector are timing out. This is true for both attempts to access a repo through the mirror, and on the mirror status page listed at the top of https://www.jenkins.io/download/mirrors/

### Reproduction steps

1. Attempt to make a HTTP request to mirrors.jenkins.io, or via the mirrors status page.
2. Wait for the timeout.

**Comment by MarkEWaite** [comment] 2023-07-09 18:04
I can't duplicate the issue.  When I open the mirror status page, it responds immediately.

The response time graph for the last 24 hours from my location shows a brief spike about 8 hours ago, but nothing more recent than that.

![image](https://github.com/jenkins-infra/helpdesk/assets/156685/5a156504-fc73-41f6-aca9-596ced34fdd3)

Are you sure that the issue is not somehow local to your environment?

**Comment by cinnion** [comment] 2023-07-09 18:49
Thanks for getting back to me on a Sunday Mark. It is really appreciated.

Interestingly, when I do it from any connection going through my home
internet (including my cell phone), I get the timeout, but through my cell
phone's 5G (T-mobile), I get a mirrorbits map showing a yellow dot in KS, a
green dot near Richmond, and several dots overseas.  Is there any GeoDNS
based addressing for mirrors.jenkins.io/get.jenkins.io?? I am having no
other problems with other sites, and my home DNS bypasses my NSP and goes
straight to the .IO root servers to azure-dns to get the address of
20.7.178.24. Unfortunately, I have not found any way to tell what address
is being used by the browser on my cell phone.  I have been having this
problem since yesterday evening and initially figured that perhaps there
was maintenance ongoing without checking to verify that that was the case.

Regards,
- Doug

**Comment by MarkEWaite** [comment] 2023-07-09 18:57
> Is there any GeoDNS based addressing for mirrors.jenkins.io/get.jenkins.io??

The addresses of mirrors.jenkins.io and get.jenkins.io are not specific to any geography.

The IP address of mirrors.jenkins.io and get.jenkins.io changed on Friday.  Possibly you have something that is ignored the DNS time to live settings and is caching an incorrect IP address?

**Comment by cinnion** [comment] 2023-07-09 19:12
Thanks Mark! I have tried flushing my bind cache and the cache in chrome,
but no progress. I am wondering if perhaps one of the azure-dns servers has
old data that I am getting back. I will investigate that, as I have had my
own secondaries at providers like EasyDNS or ZoneEdit do that on me.  Can
you please let me know what the address changed to on Friday (or what it is
now resolving to for you), so that we can compare it against what I got and
included in my previous message?

**Comment by MarkEWaite** [comment] 2023-07-09 19:33
My Linux machine reports:

```
$ dig mirrors.jenkins.io
mirrors.jenkins.io.     60      IN      CNAME   public.publick8s.jenkins.io.
public.publick8s.jenkins.io. 40 IN      A       20.7.178.24
```

Public DNS lookup services confirm that address as well:

* https://www.nslookup.io/domains/mirrors.jenkins.io/dns-records/
* https://www.whatsmydns.net/dns-lookup?query=mirrors.jenkins.io&server=google
* https://www.digitalocean.com/community/tools/dns?domain=mirrors.jenkins.io

**Comment by cinnion** [comment] 2023-07-09 20:03
Thanks,

I think we can rule out the DNS, since that is the same address I saw. I am
going to try some other things on my end, including reconnecting the VM on
which I was trying to do the install outside my firewall and trying again.
Between that and explicit logging of HTTP traffic across my firewall, maybe
I can find out what is going on.

**Comment by MarkEWaite** [comment] 2023-07-09 22:03
Thanks.  I'm closing this issue since I expect there is nothing that the Jenkins infra team can do to assist.  If your investigation shows that I'm wrong, we can always reopen the ticket.

**Closed by MarkEWaite** 2023-07-09 22:03 UTC
Labels: triage
