### ISSUE TITLE
Plugin site improperly displays GH releases with empty title

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/helpdesk#4331] opened 2024-10-07 08:13 UTC
### Service(s)

plugins.jenkins.io

### Summary

For example, https://github.com/jenkinsci/credentials-plugin/releases/tag/1381.v2c3a_12074da_b_

GH shows:

> <img width="1156" alt="Screenshot 2024-10-07 at 10 12 08" src="https://github.com/user-attachments/assets/a7c11073-6851-4bf6-9729-0ae2dadac772">

Plugins site shows:

> <img width="1636" alt="Screenshot 2024-10-07 at 10 12 19" src="https://github.com/user-attachments/assets/fe72e613-9101-490c-90ff-c2cbdb4707c0">

Given title is optional and defaults to the tag name if unspecified, this seems like a bug on the plugins site.

**Comment by alecharp** [comment] 2024-10-08 14:37
Hi @daniel-beck. I noticed that it happens also on https://plugins.jenkins.io/credentials/releases/#version_1371.1373.v4eb_fa_b_7161e9 which seems to be both related to security releases. Has something been done differently on those releases?

I'll check the plugin-site code to see where the release title is gathered from.

**Comment by alecharp** [comment] 2024-10-08 14:52
from https://github.com/jenkins-infra/plugin-site/blob/18a6674e117a109630ba6b2d1357bec7c64f0439/plugins/plugin-site/src/components/PluginReleases.jsx#L24, the data seems to be coming from https://plugin-site-issues.jenkins.io/api/plugin/credentials/releases where the "name" of the release 1381.v2c3a_12074da_b_ is not the version but `credentials-plugin`.

**Comment by timja** [comment] 2024-10-08 17:23
I expect should be `release.name || release.tag_name`

**Comment by daniel-beck** [comment] 2024-10-08 21:16
> Has something been done differently on those releases?

I created them manually (sort of), not specifying an explicit release name (as it's not needed by GH when it would be the same as the tag), perhaps unlike what usual JEP-229 scripts do.

I expect that @timja's correct about what the solution should be to be consistent with GH.

**Comment by alecharp** [comment] 2024-10-10 09:09
Yes so the problem is that the name was empty when created. And the value was "stored".
I wonderer is we can discard the "stored" value by restarting the docker-plugin-site-issues or something like that. I don't know how that works.

**Comment by timja** [comment] 2024-10-10 14:12
Isn't it still empty though?

**Comment by alecharp** [comment] 2024-10-11 09:23
You can assign this to me, I'm trying to solve it and add tests for it.

**Comment by dduportal** [comment] 2024-10-15 08:48
- Fixes by @alecharp on the "plugins-issues" component had been deployed to production:
  - https://github.com/jenkins-infra/docker-plugin-site-issues/pull/34
  - https://github.com/jenkins-infra/helm-charts/pull/1384
  - https://github.com/jenkins-infra/kubernetes-management/pull/5799
- Build of plugins-site had been triggered manually: let's see the outcome (if I'm not mistaken, this build should retrieve data from the freshly deployed plugin-issues")

**Comment by dduportal** [comment] 2024-10-15 09:04
Looks good, thanks folks!

![Capture d’écran 2024-10-15 à 11 03 57](https://github.com/user-attachments/assets/ab322cf3-6109-4429-8060-ff27da9ab011)

**Closed by dduportal** 2024-10-15 09:04 UTC
Labels: bug, plugins.jenkins.io
