### ISSUE TITLE
Helm-Charts releases are blocked

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/helpdesk#4439] opened 2024-12-05 10:52 UTC
### Service(s)

Plugin Health Scoring

### Summary

Looking at the recent activity on https://github.com/jenkins-infra/helm-charts, Plugin Health Scoring cannot be released because of a 422 on GitHub Release API.
The workflow is failing: https://github.com/jenkins-infra/helm-charts/actions/runs/12177367403/job/33967562418

**Comment by dduportal** [comment] 2024-12-06 08:18
problem is now fixed.

- Caused by https://github.com/jenkins-infra/helm-charts/pull/1462 which was merged without bumping the Chart version (checks was failing but it was merged anyway).
- Fixed by merging https://github.com/jenkins-infra/helm-charts/pull/1464 which bumped the chart version for the same geoipupdate chart


Plugin Helath Scoring has been released: https://github.com/jenkins-infra/helm-charts/releases/tag/plugin-health-scoring-3.0.5 and this new released picked for deployment: https://github.com/jenkins-infra/kubernetes-management/pull/5990

**Closed** 2024-12-06 08:20 UTC
Labels: bug, helpdesk, helm

**Comment by alecharp** [comment] 2024-12-06 08:25
Thank you!
