### ISSUE TITLE
No documentation and no javadoc shown on my plugin page

### ISSUE THREAD

**Issue by c3p0-maif** [jenkins-infra/helpdesk#4332] opened 2024-10-08 12:24 UTC
### Service(s)

plugins.jenkins.io

### Summary

hi, on my plugin page (https://plugins.jenkins.io/shared-library-version-override/), the github README.md page is not taken for documentation building.  
Another things : the javadoc pages seems to be not uploaded as well.  
Releases and Issues are OK.  
I don't know about "Heath score" page.  

What i am missing ?

**Comment by MarkEWaite** [comment] 2024-10-08 12:49
> on my plugin page (https://plugins.jenkins.io/shared-library-version-override/), the github README.md page is not taken for documentation building.

I'm not sure what's missing.  As far as I understand the generation of pages for plugins.jenkins.io, the [pom file of the most recent release](https://repo.jenkins-ci.org/ui/repos/tree/PomView/releases/io/jenkins/plugins/shared-library-version-override/19.v3a_c975738d4a_/shared-library-version-override-19.v3a_c975738d4a_.pom) is read for the {{project.url}} attribute.  Line 11 of that pom file shows the attribute as `https://github.com/jenkinsci/shared-library-version-override-plugin`

More investigation is needed.  I'll report more details as I learn them.

> javadoc pages seems to be not uploaded as well

Thanks for noting that as well.  Jenkins 2.479 has released but the [Jenkins core javadoc](https://javadoc.jenkins-ci.org/index-core.html) still reports Jenkins 2.478.  I think that means there is a problem in Javadoc generation as well.  That is a separate process from the generation of the plugins site.

> I don't know about "Heath score" page.

Plugin health score is known to not be generated.  We have an [outage](https://status.jenkins.io/issues/2024-07-02-publicheathscore-outage/) posted on [status.jenkins.io](https://status.jenkins.io/) because the maintainer has been focused on Spring Security 6 Upgrade in preparation for the 30 Oct 2024 release.  We hope to have plugin health scores calculated again by the end of November.

**Comment by timja** [comment] 2024-10-08 12:59
(from my cursory look I didn't see anything missing)

**Comment by c3p0-maif** [comment] 2024-10-10 11:03
[heart]         POTTIERS Cyril reacted to your message:
________________________________

**Comment by MarkEWaite** [comment] 2024-10-11 13:00
> Plugin health score is known to not be generated. We have an [outage](https://status.jenkins.io/issues/2024-07-02-publicheathscore-outage/) posted on [status.jenkins.io](https://status.jenkins.io/) because the maintainer has been focused on Spring Security 6 Upgrade in preparation for the 30 Oct 2024 release. We hope to have plugin health scores calculated again by the end of November.

[Plugin health score](https://plugins.jenkins.io/shared-library-version-override/healthscore/) is now reported for the plugin.

**Comment by dduportal** [comment] 2024-10-15 07:11
Closing the issue as the problem is now resolved (and health score is computed!). Thanks!

**Closed by dduportal** 2024-10-15 07:11 UTC
Labels: plugins.jenkins.io

**Comment by c3p0-maif** [comment] 2024-10-15 07:15
All is OK now ! thanks
