### ISSUE TITLE
 https://updates.jenkins.io/download/plugins/ionicons-api/70.v2959a_b_74e3cf/ionicons-api.hpi

### ISSUE THREAD

**Issue by devteam-pw** [jenkins-infra/helpdesk#4065] opened 2024-04-25 12:16 UTC
### Problem with this page

[Ionicons API](https://updates.jenkins.io/download/plugins/ionicons-api/) page

### Expected behavior

link should work 

### Actual behavior

link is not working

**Comment by lemeurherve** [comment] 2024-04-25 12:29
Just tried the "latest" and the last version ones from https://updates.jenkins.io/download/plugins/ionicons-api/ without any issue.

@devteam-pw can you specify which link(s) doesn't work for you?

**Comment by devteam-pw** [comment] 2024-04-26 02:43
I am getting connect timeout

**Comment by lemeurherve** [comment] 2024-04-26 07:55
@devteam-pw we need more details to help you.

On which URL specifically are you getting a connection timeout?

Could you please paste here the output to a call with `curl --verbose --output /dev/null --location <THE_URL_IN_QUESTION>` if you're on Linux or Mac for example?

**Comment by lemeurherve** [comment] 2024-04-30 08:45
@devteam-pw can you give us more details?

Without any feedback from you we'll have to close this issue.

**Comment by dduportal** [comment] 2024-05-02 07:52
As described on above comments, the URL works as expected and the issue is most probably on the requested side (internal HTTP proxy, firewall, blocking-list on this URL, etc.) unless proven so.

Closing as no answer from the requester.

**Closed by dduportal** 2024-05-02 07:52 UTC
Labels: updates.jenkins.io
