### ISSUE TITLE
[plugin-health-scoring] Configure new job on ci.jenkins.io

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/helpdesk#3961] opened 2024-02-26 15:45 UTC
I created https://github.com/jenkins-infra/plugin-health-scoring/pull/472 to be able to fetch and store the reports of the Plugin Health Scoring project.
This was created to solve https://github.com/jenkins-infra/plugin-health-scoring/issues/373 which is to create a static file export of the scores API.

This new Jenkinsfile is used to fetch the report file from the application API and store it on `reports.jenkins.io` to be used by `plugins.jenkins.io` (this has to be changed, one the files are available on `reports.jenkins.io`). This would ensure that the health reports are always available, even if not the most up to date.

**Comment by dduportal** [comment] 2024-04-03 12:08
As confirmed with @alecharp and @lemeurherve:

* The goal is to decouple the Plugin Site generation from the Plugin health Score webservice. The latter is NOT an highly available system.
* The proposed solution is to implement a regular report generation by the Plugin Health Score system: a static file would be hosted in reports.jenkins.io (which is an highly available system which only serves static files). It should replace the request(s?) when generating the Plugin Site made to the Plugin Health Score API.

Task list, as discussed during the infra weekly meeting of the 2 April 2024:

* Create a second job for plugin health in ci.jenkins.io which will use the `Jenkinsfile_report` (see https://github.com/jenkins-infra/plugin-health-scoring/pull/472) instead of the default `Jenkinsfile`.
  * Proposed name: `plugin-health-scoring-reports`  
  * This job must have a different set of GH notification (we know how to that since https://github.com/jenkins-infra/helpdesk/issues/2778#issuecomment-1959565465) with the GH checks setup AND the custom SCM trait plugin (might require installing it on ci.jenkins.io)
  * The intent of this Job is to provide a set of publicly available CI checks and the report would be archived on each build to check "how it looks". It would ensure any public contribution can be verified as much as posible.
 
* Create a second job for plugin health in **infra.ci.jenkins.io** which will use the `Jenkinsfile_report` (see https://github.com/jenkins-infra/plugin-health-scoring/pull/472) instead of the default `Jenkinsfile`.
  * Proposed name: `plugin-health-scoring-reports`  
  * This job must have a different set of GH notification (we know how to that since https://github.com/jenkins-infra/helpdesk/issues/2778#issuecomment-1959565465) with the custom SCM trait plugin. No GH checks (default on this controller)
  * No PR, only the principal branch should be watched
  * The intent of this Job is to provide a safe continuous deployment: each (verified) commit on the principal branch should be deployed to reports.jenkins.io.

**Comment by dduportal** [comment] 2024-04-03 12:20
Update: 

On ci.jenkins.io, the `Infra` top-level item is a GitHub organization folder which mean we cannot add the new job with a different Jenkinsfile.
On short term, I've created a top-level folder named "Jenkins Infra". The idea is to move all the `Infra` jobs into this folder but that will be a distinct issue to track it.

**Comment by dduportal** [comment] 2024-04-03 15:31
> Ping @alecharp , you'll have to rework the `Jenkinsfile_report `pipeline a bit to ensure it works.
> 
> Sounds like a scripted syntax could be better given you are using Groovy variables which values changes during pipeline execution (e.g. after the initial parsing)

As discussed with @alecharp: the plugin-health-scoring repository does not need the SCM build status for reports.
It means that a job on ci.jenkins.io for the report has no meaning (no feedback loop means no one will look at it).

Somehow, the report generation should be moved to https://github.com/jenkins-infra/infra-reports/ as it is only an infra requirement and it has no coupling with the code (except that, of course, the API may change but versioning APi path could help AND if it breaks we know where @alecharp lives :p)


As such, I proposer the following amendment to the above comments:

- No ci.jenkins.io jobs will be added (I'll delete what I created)
- The pipeline and code required to generate report will be moved to infra-report
- The (new) infra.ci job will use infra-reports repository

**Comment by alecharp** [comment] 2024-04-03 15:39
> As discussed with @alecharp: the plugin-health-scoring repository does not need the SCM build status for reports.
It means that a job on ci.jenkins.io for the report has no meaning (no feedback loop means no one will look at it).

Well, I would prefer that the `main` branch status (and release process) to be blocked because of this report build.

> if it breaks we know where @alecharp lives

No you don't ;) 

> No ci.jenkins.io jobs will be added (I'll delete what I created)

Yes, no need for that.

---

For the current build issue, the variable `URL` needs to be renamed in the pipeline and in the bash script to `HEALTH_URL`. This is because `URL` is a Java class, so it's "reserved".

**Comment by alecharp** [comment] 2024-04-03 15:42
If we want to keep the build as it is, we should disable the build of pull requests.

**Comment by dduportal** [comment] 2024-04-03 15:44
Thanks for the feedbacks @alecharp ! We'll go for the migration to infra-reports to avoid having too much "directly unrelated" code in the PHS repository. WDYT?

**Comment by dduportal** [comment] 2024-04-03 16:16
- Job creation on infra.ci: https://github.com/jenkins-infra/kubernetes-management/pull/5108

**Comment by dduportal** [comment] 2024-04-04 11:50
- @alecharp did fix the `Jenkinsfile_report` and we saw the ci.jenkins.io build being successful 👍 
- The ci.jenkins.io top-level folder named "Jenkins Infra" has been deleted (with its content)
- The infra.ci "report" job is available at https://infra.ci.jenkins.io/job/reports/job/plugin-health-scoring/ but did not picked any pipeline

Next steps: 

- PR to import the `Jenkinsfile_report` in jenkins-infra/infra-reports
- Once merged, ensure the report is published on reports.jenkins.io as expected
- Remove `Jenkinsfile_report` (and its associated scripts/resources) from https://github.com/jenkins-infra/plugin-health-scoring
- Open a new issue to track the use of this new report for the plugin-site generation

**Comment by dduportal** [comment] 2024-04-04 16:28
- Initial import of the report generation: https://github.com/jenkins-infra/infra-reports/pull/63 (to review)
- Initial deployed report can bee seen in https://reports.jenkins.io/plugin-health-scoring/scores-PR-63.json (will be removed once merged)

**Comment by alecharp** [comment] 2024-04-08 15:26
By the way @dduportal, the files on the report are not updated as often as I think they should. But I don't have access to infra.ci.jenkins.io to check on the logs.

**Comment by dduportal** [comment] 2024-04-09 06:36
> By the way @dduportal, the files on the report are not updated as often as I think they should. But I don't have access to infra.ci.jenkins.io to check on the logs.

It is once a day: https://github.com/jenkins-infra/infra-reports/blob/8f01522c57477e2d8fac72389d68579a3b9348e8/plugin-health-scoring/Jenkinsfile#L1 


I changed it to apply the report defaults but given how it works (fast to run, few errors), we can run it hourly or even every 5 minutes. Looks like the whole job takes 45 to 55s average so we can run it often!

WDYT?

**Comment by dduportal** [comment] 2024-04-09 06:37
> Both next setups are merged. Do you want to track the improvement here or in a separate ticket and close the current one @dduportal?

wow, efficient! Thanks!

**Comment by dduportal** [comment] 2024-04-09 08:18
- PR opened: https://github.com/jenkins-infra/infra-reports/pull/66 and merged for hourly reports generation
- Cleaned up PR-based reports (will need additional work on infra-report but of the scope here)


Many thanks @alecharp @lemeurherve !

**Closed by dduportal** 2024-04-09 08:18 UTC
Labels: plugin-health-scoring
