### ISSUE TITLE
The ssh-credentials plugin released an hour ago is not visible from updates.jenkins.io

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#4198] opened 2024-07-26 02:06 UTC
### Service(s)

Update center

### Summary

The ssh-credentials plugin release [343.v884f71d78167/](http://repo.jenkins-ci.org/ui/repos/tree/General/releases/org/jenkins-ci/plugins/ssh-credentials/343.v884f71d78167/) was released an hour ago, but when I open https://updates.jenkins.io/latest/ it is and use the URL https://updates.jenkins.io/latest/ssh-credentials.hpi?mirrorlist , a previous release is reported instead of the release from an hour ago

### Reproduction steps

1. Open https://updates.jenkins.io/latest/ssh-credentials.hpi?mirrorlist and confirm that 342.ve5a_f1db_5a_132 while Artifactory shows that https://repo.jenkins-ci.org/ui/repos/tree/General/releases/org/jenkins-ci/plugins/ssh-credentials/343.v884f71d78167/ is available

**Comment by dduportal** [comment] 2024-07-26 05:34
- Cause: The update_center times out when uploading to the `pkg` VM. Caused by https://github.com/jenkins-infra/helpdesk/issues/4196
- Need to investigate (top priority for now) as the Ip is allowed in Terarform: https://github.com/jenkins-infra/aws/blob/4ff43bad51c394bda8690f814a47291b4606d6d1/network.tf#L23 (https://github.com/jenkins-infra/shared-tools/blob/27eb1153c63f05b4b6175f6a8d1bd332c2865157/terraform/modules/jenkins-infra-shared-data/outputs.tf#L16)

**Comment by dduportal** [comment] 2024-07-26 06:03
> * Cause: The update_center times out when uploading to the `pkg` VM. Caused by [Restrict SSH to all VMs from VPN #4196](https://github.com/jenkins-infra/helpdesk/issues/4196)
> 
>     * Need to investigate (top priority for now) as the Ip is allowed in Terarform: https://github.com/jenkins-infra/aws/blob/4ff43bad51c394bda8690f814a47291b4606d6d1/network.tf#L23 (https://github.com/jenkins-infra/shared-tools/blob/27eb1153c63f05b4b6175f6a8d1bd332c2865157/terraform/modules/jenkins-infra-shared-data/outputs.tf#L16)

Previous comment is mistaken: it's not the trusted.ci -> pkg VM SSH connection which is timeouting.
But it is the pkg VM -> Azure `azcopy` sync command. 

*Cause:* After finishing with https://github.com/jenkins-infra/helpdesk/issues/4196, I've cleaned up the manual NSG leftovers in CloudBees AWS. It has the effect to remove the outbound HTTP rules that I forgot.

Fix in https://github.com/jenkins-infra/aws/pull/560

**Comment by dduportal** [comment] 2024-07-26 06:28
Update:

- https://github.com/jenkins-infra/aws/pull/560 has been merged. Had to run the Terraform job 3 time to ensure all NSG rules were cleanly removed and re-created.
- Update Center is back to success:
  -  https://get.jenkins.io/plugins/ssh-credentials/343.v884f71d78167/ssh-credentials.hpi?mirrorlist Is nos answering (fallback only until the mirrors picks the new plugin freshly uploaded)
  - 
<img width="1885" alt="Capture d’écran 2024-07-26 à 08 27 57" src="https://github.com/user-attachments/assets/ac842832-715c-413c-b324-1a7c7db16328">

**Comment by dduportal** [comment] 2024-07-26 08:11
Closing as the plugin is now availbe on multiple mirrors and is visible in ci.jenkins.io.

**Closed by dduportal** 2024-07-26 08:11 UTC
Labels: updateCenter

**Comment by MarkEWaite** [comment] 2024-07-26 10:34
Thanks very much!
