### ISSUE TITLE
Failing to find jenkins.war in repo.azure.jenkins.io

### ISSUE THREAD

**Issue by aytuncbeken** [jenkins-infra/helpdesk#4157] opened 2024-06-29 15:35 UTC
### Service(s)

Azure, ci.jenkins.io

### Summary

While running a PR build for the new release of my plugin, build is failing to find jenkins-executable-war in in azure-proxy (https://repo.azure.jenkins.io/).
You can see the detailed logs from here https://ci.jenkins.io/job/Plugins/job/multibranch-action-triggers-plugin/job/PR-33/5/console

Maven build is working fine on local. 

### Reproduction steps

You can rebuild this job https://ci.jenkins.io/job/Plugins/job/multibranch-action-triggers-plugin/job/PR-33/5/console

**Comment by smerle33** [comment] 2024-07-01 14:51
Hi @aytuncbeken,

it looks like the PR 33 has been merged so we cannot check the build output. 
However we see the following error on the main branch:

```
09:22:39  [ERROR] -> [Help 1]
09:22:39  org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project multibranch-action-triggers: Could not resolve dependencies for project io.jenkins.plugins:multibranch-action-triggers:jar:1.8.8-SNAPSHOT
09:22:39  dependency: org.jenkins-ci.main:jenkins-war:executable-war:2.401.3 (test)
09:22:39  	Could not find artifact org.jenkins-ci.main:jenkins-war:executable-war:2.401.3 in azure-proxy (https://repo.azure.jenkins.io/)
```

`org.jenkins-ci.main:jenkins-war:executable-war:2.401.3` is expected not to be found as it's not existing on repo.jenkins-ci.org 

https://repo.jenkins-ci.org/artifactory/public/org/jenkins-ci/main/jenkins-war/

it sound like it's more a pom or parent-pom issue than an infrastructure issue.

**Comment by dduportal** [comment] 2024-07-01 16:07
Update: @timja @MarkEWaite @basil @gounthar if you have 2 min. to spare, could you help us on this one? 
We tried the following change without any success:

- Local reproduction: nope. Same as @aytuncbeken (e.g. the error only appears on ci.jenkins.io)
- We tried to run on another ACP (`azure-internal` instead of `azure`): same error
- We tried to fix the `WARNING` about duplicated `dependendy`: same error
- We tried to use Java 11 instead of 8: same error
- We tried to bump the Pom parent to latest (with Java 11): same error

We ended today's analaysis with a build with the `--no-transfer-progress` removed: you can see the build log here: https://gist.github.com/dduportal/c06e3100c44d1573c872927da1c5a3ca.

Alas we don't see anything obvious explaining the behavior: we don't have this on other plugins so not sure what is the real problem. The last build is not helpful as we do not see the explicit client-side error.

**Comment by dduportal** [comment] 2024-07-01 16:11
Additional checks we did:

- From our datadog logs, we see the HTTP/404 error is on the following URI: https://repo.azure.jenkins.io/org/jenkins-ci/main/jenkins-war/2.401.3/jenkins-war-2.401.3.executable-war. The corresponding file on Artifactory does not exist either: https://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/2.401.3/jenkins-war-2.401.3.executable-war. We clearly are missing something since the error does NOT happen without ACP 🤔 
- The effective POM shows the `executable-war` type for the dependency comes from the pom plugin parent. Confirmed by https://github.com/jenkinsci/plugin-pom/blob/e401ce1de3334bc971c879cc5bd141a7d438e92a/pom.xml#L246. I believe the next step for us would be to teach ourselves about the type `executable-war` for artefacts

**Closed** 2024-07-01 17:06 UTC
Labels: azure, ci.jenkins.io

**Comment by basil** [comment] 2024-07-01 17:57
https://ci.jenkins.io/job/Plugins/job/multibranch-action-triggers-plugin/job/master/64/

**Comment by aytuncbeken** [comment] 2024-07-03 19:09
Hi, 

I have tried a dummy build with a test PR. It is working. https://ci.jenkins.io/job/Plugins/job/multibranch-action-triggers-plugin/job/PR-37/1/console

Thanks for jumping in so quickly and fixing the issue! 

Also thanks @basil  for the changes on the pom too.
